with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}.go"

packages:
  github.com/aprxty3/your_persona_controller.git/internal/domain/account:
    config:
      all: true
  github.com/aprxty3/your_persona_controller.git/internal/domain/content:
    config:
      all: true
  github.com/aprxty3/your_persona_controller.git/internal/domain/deletionrequest:
    config:
      all: true
  github.com/aprxty3/your_persona_controller.git/internal/domain/testresult:
    config:
      all: true
  github.com/aprxty3/your_persona_controller.git/internal/application/assessment:
    config:
      all: true
  github.com/aprxty3/your_persona_controller.git/internal/application/auth:
    config:
      all: true
  github.com/aprxty3/your_persona_controller.git/internal/application/deletionrequest:
    config:
      all: true
  github.com/aprxty3/your_persona_controller.git/internal/application/guestpurge:
    config:
      all: true
  github.com/aprxty3/your_persona_controller.git/internal/application/pdf:
    config:
      all: true
  github.com/aprxty3/your_persona_controller.git/internal/application/user_dashboard:
    config:
      all: true
  github.com/aprxty3/your_persona_controller.git/pkg/taskqueue:
    config:
      all: true
  github.com/aprxty3/your_persona_controller.git/internal/infrastructure/mailer:
    config:
      all: true
