// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	taskqueue "github.com/aprxty3/your_persona_controller.git/pkg/taskqueue"
	mock "github.com/stretchr/testify/mock"
)

// MockDispatcher is an autogenerated mock type for the Dispatcher type
type MockDispatcher struct {
	mock.Mock
}

type MockDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDispatcher) EXPECT() *MockDispatcher_Expecter {
	return &MockDispatcher_Expecter{mock: &_m.Mock}
}

// EnqueueAnonymize provides a mock function with given fields: ctx, payload
func (_m *MockDispatcher) EnqueueAnonymize(ctx context.Context, payload taskqueue.AnonymizeUserPayload) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueAnonymize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, taskqueue.AnonymizeUserPayload) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDispatcher_EnqueueAnonymize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueAnonymize'
type MockDispatcher_EnqueueAnonymize_Call struct {
	*mock.Call
}

// EnqueueAnonymize is a helper method to define mock.On call
//   - ctx context.Context
//   - payload taskqueue.AnonymizeUserPayload
func (_e *MockDispatcher_Expecter) EnqueueAnonymize(ctx interface{}, payload interface{}) *MockDispatcher_EnqueueAnonymize_Call {
	return &MockDispatcher_EnqueueAnonymize_Call{Call: _e.mock.On("EnqueueAnonymize", ctx, payload)}
}

func (_c *MockDispatcher_EnqueueAnonymize_Call) Run(run func(ctx context.Context, payload taskqueue.AnonymizeUserPayload)) *MockDispatcher_EnqueueAnonymize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(taskqueue.AnonymizeUserPayload))
	})
	return _c
}

func (_c *MockDispatcher_EnqueueAnonymize_Call) Return(_a0 error) *MockDispatcher_EnqueueAnonymize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDispatcher_EnqueueAnonymize_Call) RunAndReturn(run func(context.Context, taskqueue.AnonymizeUserPayload) error) *MockDispatcher_EnqueueAnonymize_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueEmail provides a mock function with given fields: ctx, payload, queue
func (_m *MockDispatcher) EnqueueEmail(ctx context.Context, payload taskqueue.SendEmailPayload, queue string) error {
	ret := _m.Called(ctx, payload, queue)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, taskqueue.SendEmailPayload, string) error); ok {
		r0 = rf(ctx, payload, queue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDispatcher_EnqueueEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueEmail'
type MockDispatcher_EnqueueEmail_Call struct {
	*mock.Call
}

// EnqueueEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - payload taskqueue.SendEmailPayload
//   - queue string
func (_e *MockDispatcher_Expecter) EnqueueEmail(ctx interface{}, payload interface{}, queue interface{}) *MockDispatcher_EnqueueEmail_Call {
	return &MockDispatcher_EnqueueEmail_Call{Call: _e.mock.On("EnqueueEmail", ctx, payload, queue)}
}

func (_c *MockDispatcher_EnqueueEmail_Call) Run(run func(ctx context.Context, payload taskqueue.SendEmailPayload, queue string)) *MockDispatcher_EnqueueEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(taskqueue.SendEmailPayload), args[2].(string))
	})
	return _c
}

func (_c *MockDispatcher_EnqueueEmail_Call) Return(_a0 error) *MockDispatcher_EnqueueEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDispatcher_EnqueueEmail_Call) RunAndReturn(run func(context.Context, taskqueue.SendEmailPayload, string) error) *MockDispatcher_EnqueueEmail_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueuePDFGeneration provides a mock function with given fields: ctx, payload
func (_m *MockDispatcher) EnqueuePDFGeneration(ctx context.Context, payload taskqueue.GeneratePDFPayload) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for EnqueuePDFGeneration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, taskqueue.GeneratePDFPayload) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDispatcher_EnqueuePDFGeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueuePDFGeneration'
type MockDispatcher_EnqueuePDFGeneration_Call struct {
	*mock.Call
}

// EnqueuePDFGeneration is a helper method to define mock.On call
//   - ctx context.Context
//   - payload taskqueue.GeneratePDFPayload
func (_e *MockDispatcher_Expecter) EnqueuePDFGeneration(ctx interface{}, payload interface{}) *MockDispatcher_EnqueuePDFGeneration_Call {
	return &MockDispatcher_EnqueuePDFGeneration_Call{Call: _e.mock.On("EnqueuePDFGeneration", ctx, payload)}
}

func (_c *MockDispatcher_EnqueuePDFGeneration_Call) Run(run func(ctx context.Context, payload taskqueue.GeneratePDFPayload)) *MockDispatcher_EnqueuePDFGeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(taskqueue.GeneratePDFPayload))
	})
	return _c
}

func (_c *MockDispatcher_EnqueuePDFGeneration_Call) Return(_a0 error) *MockDispatcher_EnqueuePDFGeneration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDispatcher_EnqueuePDFGeneration_Call) RunAndReturn(run func(context.Context, taskqueue.GeneratePDFPayload) error) *MockDispatcher_EnqueuePDFGeneration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDispatcher creates a new instance of MockDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDispatcher {
	mock := &MockDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
