// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPDFStorage is an autogenerated mock type for the PDFStorage type
type MockPDFStorage struct {
	mock.Mock
}

type MockPDFStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPDFStorage) EXPECT() *MockPDFStorage_Expecter {
	return &MockPDFStorage_Expecter{mock: &_m.Mock}
}

// DeleteByURL provides a mock function with given fields: ctx, rawURL
func (_m *MockPDFStorage) DeleteByURL(ctx context.Context, rawURL string) error {
	ret := _m.Called(ctx, rawURL)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, rawURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPDFStorage_DeleteByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByURL'
type MockPDFStorage_DeleteByURL_Call struct {
	*mock.Call
}

// DeleteByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - rawURL string
func (_e *MockPDFStorage_Expecter) DeleteByURL(ctx interface{}, rawURL interface{}) *MockPDFStorage_DeleteByURL_Call {
	return &MockPDFStorage_DeleteByURL_Call{Call: _e.mock.On("DeleteByURL", ctx, rawURL)}
}

func (_c *MockPDFStorage_DeleteByURL_Call) Run(run func(ctx context.Context, rawURL string)) *MockPDFStorage_DeleteByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPDFStorage_DeleteByURL_Call) Return(_a0 error) *MockPDFStorage_DeleteByURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPDFStorage_DeleteByURL_Call) RunAndReturn(run func(context.Context, string) error) *MockPDFStorage_DeleteByURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPDFStorage creates a new instance of MockPDFStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPDFStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPDFStorage {
	mock := &MockPDFStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
