// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTurnstileVerifier is an autogenerated mock type for the TurnstileVerifier type
type MockTurnstileVerifier struct {
	mock.Mock
}

type MockTurnstileVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTurnstileVerifier) EXPECT() *MockTurnstileVerifier_Expecter {
	return &MockTurnstileVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: ctx, token, remoteIP
func (_m *MockTurnstileVerifier) Verify(ctx context.Context, token string, remoteIP string) (bool, error) {
	ret := _m.Called(ctx, token, remoteIP)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, token, remoteIP)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, token, remoteIP)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, remoteIP)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTurnstileVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockTurnstileVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - remoteIP string
func (_e *MockTurnstileVerifier_Expecter) Verify(ctx interface{}, token interface{}, remoteIP interface{}) *MockTurnstileVerifier_Verify_Call {
	return &MockTurnstileVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, token, remoteIP)}
}

func (_c *MockTurnstileVerifier_Verify_Call) Run(run func(ctx context.Context, token string, remoteIP string)) *MockTurnstileVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTurnstileVerifier_Verify_Call) Return(_a0 bool, _a1 error) *MockTurnstileVerifier_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTurnstileVerifier_Verify_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockTurnstileVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTurnstileVerifier creates a new instance of MockTurnstileVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTurnstileVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTurnstileVerifier {
	mock := &MockTurnstileVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
