// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPasswordBreachChecker is an autogenerated mock type for the PasswordBreachChecker type
type MockPasswordBreachChecker struct {
	mock.Mock
}

type MockPasswordBreachChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordBreachChecker) EXPECT() *MockPasswordBreachChecker_Expecter {
	return &MockPasswordBreachChecker_Expecter{mock: &_m.Mock}
}

// IsBreached provides a mock function with given fields: ctx, password
func (_m *MockPasswordBreachChecker) IsBreached(ctx context.Context, password string) (bool, error) {
	ret := _m.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for IsBreached")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordBreachChecker_IsBreached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBreached'
type MockPasswordBreachChecker_IsBreached_Call struct {
	*mock.Call
}

// IsBreached is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
func (_e *MockPasswordBreachChecker_Expecter) IsBreached(ctx interface{}, password interface{}) *MockPasswordBreachChecker_IsBreached_Call {
	return &MockPasswordBreachChecker_IsBreached_Call{Call: _e.mock.On("IsBreached", ctx, password)}
}

func (_c *MockPasswordBreachChecker_IsBreached_Call) Run(run func(ctx context.Context, password string)) *MockPasswordBreachChecker_IsBreached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordBreachChecker_IsBreached_Call) Return(_a0 bool, _a1 error) *MockPasswordBreachChecker_IsBreached_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordBreachChecker_IsBreached_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockPasswordBreachChecker_IsBreached_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordBreachChecker creates a new instance of MockPasswordBreachChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordBreachChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordBreachChecker {
	mock := &MockPasswordBreachChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
