// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	redis "github.com/aprxty3/your_persona_controller.git/internal/infrastructure/cache/redis"
	mock "github.com/stretchr/testify/mock"
)

// MockOTPRateLimiter is an autogenerated mock type for the OTPRateLimiter type
type MockOTPRateLimiter struct {
	mock.Mock
}

type MockOTPRateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOTPRateLimiter) EXPECT() *MockOTPRateLimiter_Expecter {
	return &MockOTPRateLimiter_Expecter{mock: &_m.Mock}
}

// CheckAndConsume provides a mock function with given fields: ctx, scope, email
func (_m *MockOTPRateLimiter) CheckAndConsume(ctx context.Context, scope redis.OTPScope, email string) (int, error) {
	ret := _m.Called(ctx, scope, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckAndConsume")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, redis.OTPScope, string) (int, error)); ok {
		return rf(ctx, scope, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, redis.OTPScope, string) int); ok {
		r0 = rf(ctx, scope, email)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, redis.OTPScope, string) error); ok {
		r1 = rf(ctx, scope, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOTPRateLimiter_CheckAndConsume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAndConsume'
type MockOTPRateLimiter_CheckAndConsume_Call struct {
	*mock.Call
}

// CheckAndConsume is a helper method to define mock.On call
//   - ctx context.Context
//   - scope redis.OTPScope
//   - email string
func (_e *MockOTPRateLimiter_Expecter) CheckAndConsume(ctx interface{}, scope interface{}, email interface{}) *MockOTPRateLimiter_CheckAndConsume_Call {
	return &MockOTPRateLimiter_CheckAndConsume_Call{Call: _e.mock.On("CheckAndConsume", ctx, scope, email)}
}

func (_c *MockOTPRateLimiter_CheckAndConsume_Call) Run(run func(ctx context.Context, scope redis.OTPScope, email string)) *MockOTPRateLimiter_CheckAndConsume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(redis.OTPScope), args[2].(string))
	})
	return _c
}

func (_c *MockOTPRateLimiter_CheckAndConsume_Call) Return(retryAfterSeconds int, err error) *MockOTPRateLimiter_CheckAndConsume_Call {
	_c.Call.Return(retryAfterSeconds, err)
	return _c
}

func (_c *MockOTPRateLimiter_CheckAndConsume_Call) RunAndReturn(run func(context.Context, redis.OTPScope, string) (int, error)) *MockOTPRateLimiter_CheckAndConsume_Call {
	_c.Call.Return(run)
	return _c
}

// SetCooldown provides a mock function with given fields: ctx, scope, email
func (_m *MockOTPRateLimiter) SetCooldown(ctx context.Context, scope redis.OTPScope, email string) error {
	ret := _m.Called(ctx, scope, email)

	if len(ret) == 0 {
		panic("no return value specified for SetCooldown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, redis.OTPScope, string) error); ok {
		r0 = rf(ctx, scope, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPRateLimiter_SetCooldown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCooldown'
type MockOTPRateLimiter_SetCooldown_Call struct {
	*mock.Call
}

// SetCooldown is a helper method to define mock.On call
//   - ctx context.Context
//   - scope redis.OTPScope
//   - email string
func (_e *MockOTPRateLimiter_Expecter) SetCooldown(ctx interface{}, scope interface{}, email interface{}) *MockOTPRateLimiter_SetCooldown_Call {
	return &MockOTPRateLimiter_SetCooldown_Call{Call: _e.mock.On("SetCooldown", ctx, scope, email)}
}

func (_c *MockOTPRateLimiter_SetCooldown_Call) Run(run func(ctx context.Context, scope redis.OTPScope, email string)) *MockOTPRateLimiter_SetCooldown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(redis.OTPScope), args[2].(string))
	})
	return _c
}

func (_c *MockOTPRateLimiter_SetCooldown_Call) Return(_a0 error) *MockOTPRateLimiter_SetCooldown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPRateLimiter_SetCooldown_Call) RunAndReturn(run func(context.Context, redis.OTPScope, string) error) *MockOTPRateLimiter_SetCooldown_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOTPRateLimiter creates a new instance of MockOTPRateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOTPRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOTPRateLimiter {
	mock := &MockOTPRateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
