// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionTokenStore is an autogenerated mock type for the SessionTokenStore type
type MockSessionTokenStore struct {
	mock.Mock
}

type MockSessionTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionTokenStore) EXPECT() *MockSessionTokenStore_Expecter {
	return &MockSessionTokenStore_Expecter{mock: &_m.Mock}
}

// ConsumeResetJTI provides a mock function with given fields: ctx, jti
func (_m *MockSessionTokenStore) ConsumeResetJTI(ctx context.Context, jti string) (string, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeResetJTI")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionTokenStore_ConsumeResetJTI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeResetJTI'
type MockSessionTokenStore_ConsumeResetJTI_Call struct {
	*mock.Call
}

// ConsumeResetJTI is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockSessionTokenStore_Expecter) ConsumeResetJTI(ctx interface{}, jti interface{}) *MockSessionTokenStore_ConsumeResetJTI_Call {
	return &MockSessionTokenStore_ConsumeResetJTI_Call{Call: _e.mock.On("ConsumeResetJTI", ctx, jti)}
}

func (_c *MockSessionTokenStore_ConsumeResetJTI_Call) Run(run func(ctx context.Context, jti string)) *MockSessionTokenStore_ConsumeResetJTI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionTokenStore_ConsumeResetJTI_Call) Return(userID string, err error) *MockSessionTokenStore_ConsumeResetJTI_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *MockSessionTokenStore_ConsumeResetJTI_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockSessionTokenStore_ConsumeResetJTI_Call {
	_c.Call.Return(run)
	return _c
}

// DenylistRefreshJTI provides a mock function with given fields: ctx, jti, ttl
func (_m *MockSessionTokenStore) DenylistRefreshJTI(ctx context.Context, jti string, ttl time.Duration) error {
	ret := _m.Called(ctx, jti, ttl)

	if len(ret) == 0 {
		panic("no return value specified for DenylistRefreshJTI")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, jti, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionTokenStore_DenylistRefreshJTI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DenylistRefreshJTI'
type MockSessionTokenStore_DenylistRefreshJTI_Call struct {
	*mock.Call
}

// DenylistRefreshJTI is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - ttl time.Duration
func (_e *MockSessionTokenStore_Expecter) DenylistRefreshJTI(ctx interface{}, jti interface{}, ttl interface{}) *MockSessionTokenStore_DenylistRefreshJTI_Call {
	return &MockSessionTokenStore_DenylistRefreshJTI_Call{Call: _e.mock.On("DenylistRefreshJTI", ctx, jti, ttl)}
}

func (_c *MockSessionTokenStore_DenylistRefreshJTI_Call) Run(run func(ctx context.Context, jti string, ttl time.Duration)) *MockSessionTokenStore_DenylistRefreshJTI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockSessionTokenStore_DenylistRefreshJTI_Call) Return(_a0 error) *MockSessionTokenStore_DenylistRefreshJTI_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionTokenStore_DenylistRefreshJTI_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockSessionTokenStore_DenylistRefreshJTI_Call {
	_c.Call.Return(run)
	return _c
}

// IsRefreshJTIDenylisted provides a mock function with given fields: ctx, jti
func (_m *MockSessionTokenStore) IsRefreshJTIDenylisted(ctx context.Context, jti string) (bool, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsRefreshJTIDenylisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionTokenStore_IsRefreshJTIDenylisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRefreshJTIDenylisted'
type MockSessionTokenStore_IsRefreshJTIDenylisted_Call struct {
	*mock.Call
}

// IsRefreshJTIDenylisted is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockSessionTokenStore_Expecter) IsRefreshJTIDenylisted(ctx interface{}, jti interface{}) *MockSessionTokenStore_IsRefreshJTIDenylisted_Call {
	return &MockSessionTokenStore_IsRefreshJTIDenylisted_Call{Call: _e.mock.On("IsRefreshJTIDenylisted", ctx, jti)}
}

func (_c *MockSessionTokenStore_IsRefreshJTIDenylisted_Call) Run(run func(ctx context.Context, jti string)) *MockSessionTokenStore_IsRefreshJTIDenylisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionTokenStore_IsRefreshJTIDenylisted_Call) Return(_a0 bool, _a1 error) *MockSessionTokenStore_IsRefreshJTIDenylisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionTokenStore_IsRefreshJTIDenylisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockSessionTokenStore_IsRefreshJTIDenylisted_Call {
	_c.Call.Return(run)
	return _c
}

// StoreResetJTI provides a mock function with given fields: ctx, jti, userID, ttl
func (_m *MockSessionTokenStore) StoreResetJTI(ctx context.Context, jti string, userID string, ttl time.Duration) error {
	ret := _m.Called(ctx, jti, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for StoreResetJTI")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, jti, userID, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionTokenStore_StoreResetJTI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreResetJTI'
type MockSessionTokenStore_StoreResetJTI_Call struct {
	*mock.Call
}

// StoreResetJTI is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - userID string
//   - ttl time.Duration
func (_e *MockSessionTokenStore_Expecter) StoreResetJTI(ctx interface{}, jti interface{}, userID interface{}, ttl interface{}) *MockSessionTokenStore_StoreResetJTI_Call {
	return &MockSessionTokenStore_StoreResetJTI_Call{Call: _e.mock.On("StoreResetJTI", ctx, jti, userID, ttl)}
}

func (_c *MockSessionTokenStore_StoreResetJTI_Call) Run(run func(ctx context.Context, jti string, userID string, ttl time.Duration)) *MockSessionTokenStore_StoreResetJTI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockSessionTokenStore_StoreResetJTI_Call) Return(_a0 error) *MockSessionTokenStore_StoreResetJTI_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionTokenStore_StoreResetJTI_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockSessionTokenStore_StoreResetJTI_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionTokenStore creates a new instance of MockSessionTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionTokenStore {
	mock := &MockSessionTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
