package main

import (
	"context"
	"errors"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	echo "github.com/labstack/echo/v4"
)

func main() {
	// Note: In production, load your .env using godotenv or Viper here.

	// ---------------------------------------------------------
	// 1. DEPENDENCY INJECTION (Wire)
	// ---------------------------------------------------------
	// NOTE FOR ANTIGRAVITY AGENT:
	// Uncomment the InitializeAPI call below once you have completed
	// all repositories and successfully ran `make wire` to generate wire_gen.go.

	/*
		apiKey := os.Getenv("GEMINI_API_KEY")
		model := os.Getenv("GEMINI_MODEL")
		maxConcurrent := int64(10) // Should be parsed from GEMINI_MAX_CONCURRENT

		app, err := InitializeAPI(apiKey, model, maxConcurrent)
		if err != nil {
			log.Fatalf("Failed to initialize API: %v", err)
		}
	*/

	// Placeholder fallback until Wire is generated by the Agent:
	app := echo.New()

	port := os.Getenv("APP_PORT")
	if port == "" {
		port = "8080"
	}

	// ---------------------------------------------------------
	// 2. SERVER START & GRACEFUL SHUTDOWN (Strict Rule PRD 9.5)
	// ---------------------------------------------------------

	// Start the server in a separate goroutine so it doesn't block
	go func() {
		log.Printf("Server is starting on port %s...", port)
		if err := app.Start(":" + port); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("Server forced to shutdown abruptly: %v", err)
		}
	}()

	// Create a channel to listen for OS interrupt signals
	quit := make(chan os.Signal, 1)

	// Catch SIGINT (Ctrl+C from terminal) and SIGTERM (Docker/K8s termination signal)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	// Block the main thread until a signal is received
	<-quit
	log.Println("Interrupt signal received. Shutting down server gracefully...")

	// Parse shutdown timeout from env, fallback to 30s
	timeoutStr := os.Getenv("SHUTDOWN_TIMEOUT")
	timeoutDuration, err := time.ParseDuration(timeoutStr)
	if err != nil || timeoutDuration == 0 {
		timeoutDuration = 30 * time.Second
	}

	// Create a context with the timeout
	// This tells the server it has exactly 'timeoutDuration' to finish ongoing requests (e.g. Gemini processing).
	ctx, cancel := context.WithTimeout(context.Background(), timeoutDuration)
	defer cancel()

	if err := app.Shutdown(ctx); err != nil {
		log.Fatalf("Server shutdown failed or timed out: %v", err)
	}

	log.Println("Server exited properly.")
}
