// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aprxty3/your_persona_controller.git/internal/application/assessment"
	"github.com/aprxty3/your_persona_controller.git/internal/application/auth"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/cache/redis"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/gemini"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/jwt"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/guestsession"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/referral"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/testresult"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/user"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/verificationtoken"
	asynq2 "github.com/aprxty3/your_persona_controller.git/internal/infrastructure/queue/asynq"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/stubs"
	"github.com/aprxty3/your_persona_controller.git/internal/interfaces/http"
	"github.com/aprxty3/your_persona_controller.git/internal/interfaces/http/handler"
	"github.com/aprxty3/your_persona_controller.git/internal/interfaces/http/middleware"
	"github.com/aprxty3/your_persona_controller.git/pkg/logger"
	"github.com/aprxty3/your_persona_controller.git/pkg/taskqueue"
	"github.com/hibiken/asynq"
	"github.com/labstack/echo/v4"
	redis2 "github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeAPI wires up the entire application and returns the Echo router.
func InitializeAPI(geminiAPIKey GeminiAPIKey, geminiModel GeminiModel, maxConcurrent int64, dbDSN DBDSN, redisAddr RedisAddr, redisPassword RedisPassword, redisDB int, jwtSecret JWTSecret, loggerInstance logger.Logger) (*echo.Echo, error) {
	testResultRepository := stubs.NewStubTestResultRepository()
	answerRepository := stubs.NewStubAnswerRepository()
	client, err := provideGeminiClient(geminiAPIKey, geminiModel, maxConcurrent)
	if err != nil {
		return nil, err
	}
	distributedLockService := stubs.NewStubDistributedLockService()
	idempotencyService := stubs.NewStubIdempotencyService()
	pdfQueueService := stubs.NewStubPDFQueueService()
	submitAssessmentUseCase := assessment.NewSubmitAssessmentUseCase(testResultRepository, answerRepository, client, distributedLockService, idempotencyService, pdfQueueService)
	assessmentHandler := handler.NewAssessmentHandler(submitAssessmentUseCase)
	db, err := providePostgresDB(dbDSN)
	if err != nil {
		return nil, err
	}
	repository := guestsession.NewGuestSessionRepository(db, loggerInstance)
	createGuestSessionUseCase := auth.NewCreateGuestSessionUseCase(repository, loggerInstance)
	userRepository := user.NewUserRepository(db, loggerInstance)
	verificationtokenRepository := verificationtoken.NewVerificationTokenRepository(db, loggerInstance)
	referralRepository := referral.NewReferralRepository(db, loggerInstance)
	testresultRepository := testresult.NewTestResultRepository(db, loggerInstance)
	passwordBreachChecker := auth.NewNoopBreachChecker()
	asynqClient, err := provideAsynqClient(redisAddr, redisPassword, redisDB)
	if err != nil {
		return nil, err
	}
	dispatcher := taskqueue.NewAsynqDispatcher(asynqClient)
	registerUseCase := auth.NewRegisterUseCase(db, userRepository, repository, verificationtokenRepository, referralRepository, testresultRepository, passwordBreachChecker, dispatcher, loggerInstance)
	verifyEmailOTPUseCase := auth.NewVerifyEmailOTPUseCase(userRepository, verificationtokenRepository, loggerInstance)
	redisClient, err := provideRedisClient(redisAddr, redisPassword, redisDB)
	if err != nil {
		return nil, err
	}
	otpRateLimitService := redis.NewOTPRateLimitService(redisClient)
	resendEmailOTPUseCase := auth.NewResendEmailOTPUseCase(userRepository, verificationtokenRepository, otpRateLimitService, dispatcher, loggerInstance)
	jwtService := provideJWTService(jwtSecret)
	loginUseCase := auth.NewLoginUseCase(userRepository, jwtService, loggerInstance)
	tokenStore := redis.NewTokenStore(redisClient)
	refreshTokenUseCase := auth.NewRefreshTokenUseCase(userRepository, jwtService, tokenStore, loggerInstance)
	logoutUseCase := auth.NewLogoutUseCase(jwtService, tokenStore, loggerInstance)
	logoutAllUseCase := auth.NewLogoutAllUseCase(userRepository, loggerInstance)
	forgotPasswordUseCase := auth.NewForgotPasswordUseCase(userRepository, verificationtokenRepository, otpRateLimitService, dispatcher, loggerInstance)
	verifyResetOTPUseCase := auth.NewVerifyResetOTPUseCase(userRepository, verificationtokenRepository, jwtService, tokenStore, loggerInstance)
	resetPasswordUseCase := auth.NewResetPasswordUseCase(db, userRepository, passwordBreachChecker, jwtService, tokenStore, loggerInstance)
	authHandler := handler.NewAuthHandler(createGuestSessionUseCase, registerUseCase, verifyEmailOTPUseCase, resendEmailOTPUseCase, loginUseCase, refreshTokenUseCase, logoutUseCase, logoutAllUseCase, forgotPasswordUseCase, verifyResetOTPUseCase, resetPasswordUseCase, loggerInstance)
	authMiddleware := middleware.NewAuthMiddleware(jwtService, userRepository, loggerInstance)
	echoEcho := http.SetupRouter(assessmentHandler, authHandler, authMiddleware)
	return echoEcho, nil
}

// wire.go:

// Wrapper providers to resolve concrete types using the typed aliases.
func provideGeminiClient(key GeminiAPIKey, model GeminiModel, maxConcurrent int64) (*gemini.Client, error) {
	return gemini.NewClient(string(key), string(model), maxConcurrent)
}

func providePostgresDB(dsn DBDSN) (*gorm.DB, error) {
	return postgres.NewPostgresDB(string(dsn))
}

func provideRedisClient(addr RedisAddr, password RedisPassword, db int) (*redis2.Client, error) {
	return redis.NewRedisClient(string(addr), string(password), db)
}

func provideAsynqClient(addr RedisAddr, password RedisPassword, db int) (*asynq.Client, error) {
	return asynq2.NewAsynqClient(string(addr), string(password), db)
}

func provideJWTService(secret JWTSecret) *jwtservice.JWTService {
	return jwtservice.NewJWTService(string(secret))
}
