// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	assessment2 "github.com/aprxty3/your_persona_controller.git/internal/application/assessment"
	"github.com/aprxty3/your_persona_controller.git/internal/application/auth"
	deletionrequest2 "github.com/aprxty3/your_persona_controller.git/internal/application/deletionrequest"
	"github.com/aprxty3/your_persona_controller.git/internal/application/profile"
	"github.com/aprxty3/your_persona_controller.git/internal/application/user_dashboard"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/cache/redis"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/gemini"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/jwt"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/account"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/assessment"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/deletionrequest"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/queue/asynq"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/security"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/storage/s3"
	"github.com/aprxty3/your_persona_controller.git/internal/interfaces/http"
	"github.com/aprxty3/your_persona_controller.git/internal/interfaces/http/handler"
	"github.com/aprxty3/your_persona_controller.git/internal/interfaces/http/middleware"
	"github.com/aprxty3/your_persona_controller.git/pkg/logger"
	"github.com/aprxty3/your_persona_controller.git/pkg/taskqueue"
	asynq2 "github.com/hibiken/asynq"
	"github.com/labstack/echo/v4"
	redis2 "github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeAPI wires up the entire application and returns the Echo router.
func InitializeAPI(geminiAPIKey GeminiAPIKey, geminiModel GeminiModel, maxConcurrent int64, dbDSN DBDSN, redisAddr RedisAddr, redisPassword RedisPassword, redisDB int, jwtSecret JWTSecret, s3Endpoint S3Endpoint, s3Region S3Region, s3Bucket S3Bucket, s3AccessKey S3AccessKey, s3SecretKey S3SecretKey, s3UsePathStyle S3UsePathStyle, turnstileSecretKey TurnstileSecretKey, isProduction IsProduction, allowedOrigins AllowedOrigins, loggerInstance logger.Logger) (*echo.Echo, error) {
	db, err := providePostgresDB(dbDSN)
	if err != nil {
		return nil, err
	}
	testResultRepository := assessment.NewTestResultRepository(db, loggerInstance)
	questionRepository := assessment.NewQuestionRepository(db, loggerInstance)
	userRepository := account.NewUserRepository(db, loggerInstance)
	client, err := provideGeminiClient(geminiAPIKey, geminiModel, maxConcurrent)
	if err != nil {
		return nil, err
	}
	redisClient, err := provideRedisClient(redisAddr, redisPassword, redisDB)
	if err != nil {
		return nil, err
	}
	distributedLockService := redis.NewDistributedLockService(redisClient)
	idempotencyService := redis.NewIdempotencyService(redisClient, loggerInstance)
	asynqClient, err := provideAsynqClient(redisAddr, redisPassword, redisDB)
	if err != nil {
		return nil, err
	}
	dispatcher := taskqueue.NewAsynqDispatcher(asynqClient)
	pdfQueueService := asynq.NewPDFQueueService(dispatcher)
	submitAssessmentUseCase := assessment2.NewSubmitAssessmentUseCase(db, testResultRepository, questionRepository, userRepository, client, distributedLockService, idempotencyService, pdfQueueService, loggerInstance)
	assessmentHandler := handler.NewAssessmentHandler(submitAssessmentUseCase, loggerInstance)
	questionCatalogUseCase := assessment2.NewQuestionCatalogUseCase(questionRepository, loggerInstance)
	s3Client, err := provideS3Client(s3Endpoint, s3Region, s3Bucket, s3AccessKey, s3SecretKey, s3UsePathStyle)
	if err != nil {
		return nil, err
	}
	resultUseCase := assessment2.NewResultUseCase(testResultRepository, s3Client, loggerInstance)
	resultHandler := handler.NewResultHandler(questionCatalogUseCase, resultUseCase, loggerInstance)
	insightTemplateRepository := assessment.NewInsightTemplateRepository(db, loggerInstance)
	dashboardUseCase := dashboard.NewDashboardUseCase(testResultRepository, insightTemplateRepository, loggerInstance)
	dashboardHandler := handler.NewDashboardHandler(dashboardUseCase, loggerInstance)
	guestSessionRepository := account.NewGuestSessionRepository(db, loggerInstance)
	createGuestSessionUseCase := auth.NewCreateGuestSessionUseCase(guestSessionRepository, loggerInstance)
	verificationTokenRepository := account.NewVerificationTokenRepository(db, loggerInstance)
	referralRepository := account.NewReferralRepository(db, loggerInstance)
	passwordBreachChecker := security.NewHIBPBreachChecker(loggerInstance)
	ipRateLimitService := redis.NewIPRateLimitService(redisClient)
	registerUseCase := auth.NewRegisterUseCase(db, userRepository, guestSessionRepository, verificationTokenRepository, referralRepository, testResultRepository, passwordBreachChecker, dispatcher, ipRateLimitService, loggerInstance)
	otpRateLimitService := redis.NewOTPRateLimitService(redisClient)
	accountUseCase := auth.NewAccountUseCase(userRepository, verificationTokenRepository, dispatcher, otpRateLimitService, loggerInstance)
	jwtService := provideJWTService(jwtSecret)
	tokenStore := redis.NewTokenStore(redisClient)
	sessionUseCase := auth.NewSessionUseCase(db, userRepository, verificationTokenRepository, passwordBreachChecker, jwtService, tokenStore, ipRateLimitService, loggerInstance)
	turnstileVerifier := provideTurnstileVerifier(turnstileSecretKey, loggerInstance)
	bool2 := provideIsProduction(isProduction)
	authHandler := handler.NewAuthHandler(createGuestSessionUseCase, registerUseCase, accountUseCase, sessionUseCase, turnstileVerifier, bool2, loggerInstance)
	profileUseCase := profile.NewProfileUseCase(userRepository, referralRepository, loggerInstance)
	repository := deletionrequest.NewRepository(db, loggerInstance)
	deletionUseCase := deletionrequest2.NewDeletionUseCase(userRepository, repository, loggerInstance)
	accountHandler := handler.NewAccountHandler(profileUseCase, deletionUseCase, loggerInstance)
	healthHandler := handler.NewHealthHandler(db, redisClient)
	authMiddleware := middleware.NewAuthMiddleware(jwtService, userRepository, loggerInstance)
	localeMiddleware := middleware.NewLocaleMiddleware(jwtService, userRepository, loggerInstance)
	v := provideAllowedOrigins(allowedOrigins)
	echoEcho := http.SetupRouter(assessmentHandler, resultHandler, dashboardHandler, authHandler, accountHandler, healthHandler, authMiddleware, localeMiddleware, v, bool2)
	return echoEcho, nil
}

// wire.go:

// Wrapper providers to resolve concrete types using the typed aliases.
func provideGeminiClient(key GeminiAPIKey, model GeminiModel, maxConcurrent int64) (*gemini.Client, error) {
	return gemini.NewClient(string(key), string(model), maxConcurrent)
}

func providePostgresDB(dsn DBDSN) (*gorm.DB, error) {
	return postgres.NewPostgresDB(string(dsn))
}

func provideRedisClient(addr RedisAddr, password RedisPassword, db int) (*redis2.Client, error) {
	return redis.NewRedisClient(string(addr), string(password), db)
}

func provideAsynqClient(addr RedisAddr, password RedisPassword, db int) (*asynq2.Client, error) {
	return asynq.NewAsynqClient(string(addr), string(password), db)
}

func provideJWTService(secret JWTSecret) *jwtservice.JWTService {
	return jwtservice.NewJWTService(string(secret))
}

func provideS3Client(endpoint S3Endpoint, region S3Region, bucket S3Bucket, accessKey S3AccessKey, secretKey S3SecretKey, usePathStyle S3UsePathStyle) (*s3.Client, error) {
	return s3.NewClient(string(endpoint), string(region), string(bucket), string(accessKey), string(secretKey), bool(usePathStyle))
}

func provideTurnstileVerifier(secretKey TurnstileSecretKey, log logger.Logger) auth.TurnstileVerifier {
	return security.NewTurnstileVerifier(string(secretKey), log)
}

// provideIsProduction unwraps the typed alias into the plain bool that
// router.go / auth_handler.go actually consume — those HTTP-layer files stay
// Wire-agnostic and just take a bool, matching ordinary Go convention.
func provideIsProduction(v IsProduction) bool {
	return bool(v)
}

func provideAllowedOrigins(v AllowedOrigins) []string {
	return http.ParseAllowedOrigins(string(v))
}
