// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	assessment2 "github.com/aprxty3/your_persona_controller.git/internal/application/assessment"
	"github.com/aprxty3/your_persona_controller.git/internal/application/auth"
	deletionrequest2 "github.com/aprxty3/your_persona_controller.git/internal/application/deletionrequest"
	"github.com/aprxty3/your_persona_controller.git/internal/application/profile"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/cache/redis"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/gemini"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/jwt"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/account"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/assessment"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/deletionrequest"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/persistence/postgres/testresult"
	asynq2 "github.com/aprxty3/your_persona_controller.git/internal/infrastructure/queue/asynq"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/security"
	"github.com/aprxty3/your_persona_controller.git/internal/infrastructure/stubs"
	"github.com/aprxty3/your_persona_controller.git/internal/interfaces/http"
	"github.com/aprxty3/your_persona_controller.git/internal/interfaces/http/handler"
	"github.com/aprxty3/your_persona_controller.git/internal/interfaces/http/middleware"
	"github.com/aprxty3/your_persona_controller.git/pkg/logger"
	"github.com/aprxty3/your_persona_controller.git/pkg/taskqueue"
	"github.com/hibiken/asynq"
	"github.com/labstack/echo/v4"
	redis2 "github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeAPI wires up the entire application and returns the Echo router.
func InitializeAPI(geminiAPIKey GeminiAPIKey, geminiModel GeminiModel, maxConcurrent int64, dbDSN DBDSN, redisAddr RedisAddr, redisPassword RedisPassword, redisDB int, jwtSecret JWTSecret, loggerInstance logger.Logger) (*echo.Echo, error) {
	db, err := providePostgresDB(dbDSN)
	if err != nil {
		return nil, err
	}
	repository := testresult.NewTestResultRepository(db, loggerInstance)
	answerRepository := assessment.NewAnswerRepository(db, loggerInstance)
	client, err := provideGeminiClient(geminiAPIKey, geminiModel, maxConcurrent)
	if err != nil {
		return nil, err
	}
	redisClient, err := provideRedisClient(redisAddr, redisPassword, redisDB)
	if err != nil {
		return nil, err
	}
	distributedLockService := redis.NewDistributedLockService(redisClient)
	idempotencyService := redis.NewIdempotencyService(redisClient, loggerInstance)
	pdfQueueService := stubs.NewStubPDFQueueService()
	submitAssessmentUseCase := assessment2.NewSubmitAssessmentUseCase(repository, answerRepository, client, distributedLockService, idempotencyService, pdfQueueService)
	assessmentHandler := handler.NewAssessmentHandler(submitAssessmentUseCase)
	guestSessionRepository := account.NewGuestSessionRepository(db, loggerInstance)
	createGuestSessionUseCase := auth.NewCreateGuestSessionUseCase(guestSessionRepository, loggerInstance)
	userRepository := account.NewUserRepository(db, loggerInstance)
	verificationTokenRepository := account.NewVerificationTokenRepository(db, loggerInstance)
	referralRepository := account.NewReferralRepository(db, loggerInstance)
	passwordBreachChecker := security.NewHIBPBreachChecker(loggerInstance)
	asynqClient, err := provideAsynqClient(redisAddr, redisPassword, redisDB)
	if err != nil {
		return nil, err
	}
	dispatcher := taskqueue.NewAsynqDispatcher(asynqClient)
	ipRateLimitService := redis.NewIPRateLimitService(redisClient)
	registerUseCase := auth.NewRegisterUseCase(db, userRepository, guestSessionRepository, verificationTokenRepository, referralRepository, repository, passwordBreachChecker, dispatcher, ipRateLimitService, loggerInstance)
	otpRateLimitService := redis.NewOTPRateLimitService(redisClient)
	accountUseCase := auth.NewAccountUseCase(userRepository, verificationTokenRepository, dispatcher, otpRateLimitService, loggerInstance)
	jwtService := provideJWTService(jwtSecret)
	tokenStore := redis.NewTokenStore(redisClient)
	sessionUseCase := auth.NewSessionUseCase(db, userRepository, verificationTokenRepository, passwordBreachChecker, jwtService, tokenStore, ipRateLimitService, loggerInstance)
	authHandler := handler.NewAuthHandler(createGuestSessionUseCase, registerUseCase, accountUseCase, sessionUseCase, loggerInstance)
	profileUseCase := profile.NewProfileUseCase(userRepository, referralRepository, loggerInstance)
	deletionrequestRepository := deletionrequest.NewRepository(db, loggerInstance)
	deletionUseCase := deletionrequest2.NewDeletionUseCase(userRepository, deletionrequestRepository, loggerInstance)
	accountHandler := handler.NewAccountHandler(profileUseCase, deletionUseCase, loggerInstance)
	healthHandler := handler.NewHealthHandler(db, redisClient)
	authMiddleware := middleware.NewAuthMiddleware(jwtService, userRepository, loggerInstance)
	localeMiddleware := middleware.NewLocaleMiddleware(jwtService, userRepository, loggerInstance)
	echoEcho := http.SetupRouter(assessmentHandler, authHandler, accountHandler, healthHandler, authMiddleware, localeMiddleware)
	return echoEcho, nil
}

// wire.go:

// Wrapper providers to resolve concrete types using the typed aliases.
func provideGeminiClient(key GeminiAPIKey, model GeminiModel, maxConcurrent int64) (*gemini.Client, error) {
	return gemini.NewClient(string(key), string(model), maxConcurrent)
}

func providePostgresDB(dsn DBDSN) (*gorm.DB, error) {
	return postgres.NewPostgresDB(string(dsn))
}

func provideRedisClient(addr RedisAddr, password RedisPassword, db int) (*redis2.Client, error) {
	return redis.NewRedisClient(string(addr), string(password), db)
}

func provideAsynqClient(addr RedisAddr, password RedisPassword, db int) (*asynq.Client, error) {
	return asynq2.NewAsynqClient(string(addr), string(password), db)
}

func provideJWTService(secret JWTSecret) *jwtservice.JWTService {
	return jwtservice.NewJWTService(string(secret))
}
