// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	deletionrequest "github.com/aprxty3/your_persona_controller.git/internal/domain/deletionrequest"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockRepository) Create(ctx context.Context, req *deletionrequest.DataDeletionRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *deletionrequest.DataDeletionRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *deletionrequest.DataDeletionRequest
func (_e *MockRepository_Expecter) Create(ctx interface{}, req interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, req *deletionrequest.DataDeletionRequest)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*deletionrequest.DataDeletionRequest))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *deletionrequest.DataDeletionRequest) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRepository) FindActiveByUserID(ctx context.Context, userID string) (*deletionrequest.DataDeletionRequest, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByUserID")
	}

	var r0 *deletionrequest.DataDeletionRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*deletionrequest.DataDeletionRequest, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *deletionrequest.DataDeletionRequest); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deletionrequest.DataDeletionRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByUserID'
type MockRepository_FindActiveByUserID_Call struct {
	*mock.Call
}

// FindActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) FindActiveByUserID(ctx interface{}, userID interface{}) *MockRepository_FindActiveByUserID_Call {
	return &MockRepository_FindActiveByUserID_Call{Call: _e.mock.On("FindActiveByUserID", ctx, userID)}
}

func (_c *MockRepository_FindActiveByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_FindActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_FindActiveByUserID_Call) Return(_a0 *deletionrequest.DataDeletionRequest, _a1 error) *MockRepository_FindActiveByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindActiveByUserID_Call) RunAndReturn(run func(context.Context, string) (*deletionrequest.DataDeletionRequest, error)) *MockRepository_FindActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) FindByID(ctx context.Context, id string) (*deletionrequest.DataDeletionRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *deletionrequest.DataDeletionRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*deletionrequest.DataDeletionRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *deletionrequest.DataDeletionRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deletionrequest.DataDeletionRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(_a0 *deletionrequest.DataDeletionRequest, _a1 error) *MockRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*deletionrequest.DataDeletionRequest, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindExpiredGracePeriod provides a mock function with given fields: ctx
func (_m *MockRepository) FindExpiredGracePeriod(ctx context.Context) ([]deletionrequest.DataDeletionRequest, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiredGracePeriod")
	}

	var r0 []deletionrequest.DataDeletionRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]deletionrequest.DataDeletionRequest, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []deletionrequest.DataDeletionRequest); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]deletionrequest.DataDeletionRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindExpiredGracePeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindExpiredGracePeriod'
type MockRepository_FindExpiredGracePeriod_Call struct {
	*mock.Call
}

// FindExpiredGracePeriod is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) FindExpiredGracePeriod(ctx interface{}) *MockRepository_FindExpiredGracePeriod_Call {
	return &MockRepository_FindExpiredGracePeriod_Call{Call: _e.mock.On("FindExpiredGracePeriod", ctx)}
}

func (_c *MockRepository_FindExpiredGracePeriod_Call) Run(run func(ctx context.Context)) *MockRepository_FindExpiredGracePeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_FindExpiredGracePeriod_Call) Return(_a0 []deletionrequest.DataDeletionRequest, _a1 error) *MockRepository_FindExpiredGracePeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindExpiredGracePeriod_Call) RunAndReturn(run func(context.Context) ([]deletionrequest.DataDeletionRequest, error)) *MockRepository_FindExpiredGracePeriod_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionStatus provides a mock function with given fields: ctx, id, from, to, completedAt
func (_m *MockRepository) TransitionStatus(ctx context.Context, id string, from deletionrequest.DeletionStatus, to deletionrequest.DeletionStatus, completedAt *time.Time) (bool, error) {
	ret := _m.Called(ctx, id, from, to, completedAt)

	if len(ret) == 0 {
		panic("no return value specified for TransitionStatus")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, deletionrequest.DeletionStatus, deletionrequest.DeletionStatus, *time.Time) (bool, error)); ok {
		return rf(ctx, id, from, to, completedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, deletionrequest.DeletionStatus, deletionrequest.DeletionStatus, *time.Time) bool); ok {
		r0 = rf(ctx, id, from, to, completedAt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, deletionrequest.DeletionStatus, deletionrequest.DeletionStatus, *time.Time) error); ok {
		r1 = rf(ctx, id, from, to, completedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_TransitionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionStatus'
type MockRepository_TransitionStatus_Call struct {
	*mock.Call
}

// TransitionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - from deletionrequest.DeletionStatus
//   - to deletionrequest.DeletionStatus
//   - completedAt *time.Time
func (_e *MockRepository_Expecter) TransitionStatus(ctx interface{}, id interface{}, from interface{}, to interface{}, completedAt interface{}) *MockRepository_TransitionStatus_Call {
	return &MockRepository_TransitionStatus_Call{Call: _e.mock.On("TransitionStatus", ctx, id, from, to, completedAt)}
}

func (_c *MockRepository_TransitionStatus_Call) Run(run func(ctx context.Context, id string, from deletionrequest.DeletionStatus, to deletionrequest.DeletionStatus, completedAt *time.Time)) *MockRepository_TransitionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(deletionrequest.DeletionStatus), args[3].(deletionrequest.DeletionStatus), args[4].(*time.Time))
	})
	return _c
}

func (_c *MockRepository_TransitionStatus_Call) Return(_a0 bool, _a1 error) *MockRepository_TransitionStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_TransitionStatus_Call) RunAndReturn(run func(context.Context, string, deletionrequest.DeletionStatus, deletionrequest.DeletionStatus, *time.Time) (bool, error)) *MockRepository_TransitionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, completedAt
func (_m *MockRepository) UpdateStatus(ctx context.Context, id string, status deletionrequest.DeletionStatus, completedAt *time.Time) error {
	ret := _m.Called(ctx, id, status, completedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, deletionrequest.DeletionStatus, *time.Time) error); ok {
		r0 = rf(ctx, id, status, completedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status deletionrequest.DeletionStatus
//   - completedAt *time.Time
func (_e *MockRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, completedAt interface{}) *MockRepository_UpdateStatus_Call {
	return &MockRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, completedAt)}
}

func (_c *MockRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status deletionrequest.DeletionStatus, completedAt *time.Time)) *MockRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(deletionrequest.DeletionStatus), args[3].(*time.Time))
	})
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) Return(_a0 error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, deletionrequest.DeletionStatus, *time.Time) error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
