// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	testresult "github.com/aprxty3/your_persona_controller.git/internal/domain/testresult"
)

// MockTestResultRepository is an autogenerated mock type for the TestResultRepository type
type MockTestResultRepository struct {
	mock.Mock
}

type MockTestResultRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestResultRepository) EXPECT() *MockTestResultRepository_Expecter {
	return &MockTestResultRepository_Expecter{mock: &_m.Mock}
}

// CountMonthlyUsage provides a mock function with given fields: ctx, userID
func (_m *MockTestResultRepository) CountMonthlyUsage(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountMonthlyUsage")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestResultRepository_CountMonthlyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountMonthlyUsage'
type MockTestResultRepository_CountMonthlyUsage_Call struct {
	*mock.Call
}

// CountMonthlyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTestResultRepository_Expecter) CountMonthlyUsage(ctx interface{}, userID interface{}) *MockTestResultRepository_CountMonthlyUsage_Call {
	return &MockTestResultRepository_CountMonthlyUsage_Call{Call: _e.mock.On("CountMonthlyUsage", ctx, userID)}
}

func (_c *MockTestResultRepository_CountMonthlyUsage_Call) Run(run func(ctx context.Context, userID string)) *MockTestResultRepository_CountMonthlyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_CountMonthlyUsage_Call) Return(_a0 int64, _a1 error) *MockTestResultRepository_CountMonthlyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestResultRepository_CountMonthlyUsage_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockTestResultRepository_CountMonthlyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// FindHistoryByUser provides a mock function with given fields: ctx, userID, page, limit
func (_m *MockTestResultRepository) FindHistoryByUser(ctx context.Context, userID string, page int, limit int) ([]testresult.TestResult, int64, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindHistoryByUser")
	}

	var r0 []testresult.TestResult
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]testresult.TestResult, int64, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []testresult.TestResult); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]testresult.TestResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, userID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTestResultRepository_FindHistoryByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindHistoryByUser'
type MockTestResultRepository_FindHistoryByUser_Call struct {
	*mock.Call
}

// FindHistoryByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int
//   - limit int
func (_e *MockTestResultRepository_Expecter) FindHistoryByUser(ctx interface{}, userID interface{}, page interface{}, limit interface{}) *MockTestResultRepository_FindHistoryByUser_Call {
	return &MockTestResultRepository_FindHistoryByUser_Call{Call: _e.mock.On("FindHistoryByUser", ctx, userID, page, limit)}
}

func (_c *MockTestResultRepository_FindHistoryByUser_Call) Run(run func(ctx context.Context, userID string, page int, limit int)) *MockTestResultRepository_FindHistoryByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockTestResultRepository_FindHistoryByUser_Call) Return(results []testresult.TestResult, total int64, err error) *MockTestResultRepository_FindHistoryByUser_Call {
	_c.Call.Return(results, total, err)
	return _c
}

func (_c *MockTestResultRepository_FindHistoryByUser_Call) RunAndReturn(run func(context.Context, string, int, int) ([]testresult.TestResult, int64, error)) *MockTestResultRepository_FindHistoryByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTestResultRepository creates a new instance of MockTestResultRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestResultRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestResultRepository {
	mock := &MockTestResultRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
