// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	account "github.com/aprxty3/your_persona_controller.git/internal/domain/account"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Anonymize provides a mock function with given fields: ctx, id, scrubbedEmail
func (_m *MockUserRepository) Anonymize(ctx context.Context, id string, scrubbedEmail string) error {
	ret := _m.Called(ctx, id, scrubbedEmail)

	if len(ret) == 0 {
		panic("no return value specified for Anonymize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, scrubbedEmail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Anonymize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Anonymize'
type MockUserRepository_Anonymize_Call struct {
	*mock.Call
}

// Anonymize is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - scrubbedEmail string
func (_e *MockUserRepository_Expecter) Anonymize(ctx interface{}, id interface{}, scrubbedEmail interface{}) *MockUserRepository_Anonymize_Call {
	return &MockUserRepository_Anonymize_Call{Call: _e.mock.On("Anonymize", ctx, id, scrubbedEmail)}
}

func (_c *MockUserRepository_Anonymize_Call) Run(run func(ctx context.Context, id string, scrubbedEmail string)) *MockUserRepository_Anonymize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_Anonymize_Call) Return(_a0 error) *MockUserRepository_Anonymize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Anonymize_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserRepository_Anonymize_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserRepository) Create(ctx context.Context, user *account.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *account.User
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, user *account.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*account.User))
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(_a0 error) *MockUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(context.Context, *account.User) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepository) FindByEmail(ctx context.Context, email string) (*account.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *account.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*account.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *account.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserRepository_FindByEmail_Call {
	return &MockUserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) Return(_a0 *account.User, _a1 error) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (*account.User, error)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) FindByID(ctx context.Context, id string) (*account.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *account.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*account.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *account.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserRepository_FindByID_Call {
	return &MockUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByID_Call) Return(_a0 *account.User, _a1 error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*account.User, error)) *MockUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementTokenVersion provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) IncrementTokenVersion(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementTokenVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_IncrementTokenVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementTokenVersion'
type MockUserRepository_IncrementTokenVersion_Call struct {
	*mock.Call
}

// IncrementTokenVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) IncrementTokenVersion(ctx interface{}, id interface{}) *MockUserRepository_IncrementTokenVersion_Call {
	return &MockUserRepository_IncrementTokenVersion_Call{Call: _e.mock.On("IncrementTokenVersion", ctx, id)}
}

func (_c *MockUserRepository_IncrementTokenVersion_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_IncrementTokenVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_IncrementTokenVersion_Call) Return(_a0 error) *MockUserRepository_IncrementTokenVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_IncrementTokenVersion_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRepository_IncrementTokenVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockUserRepository) Update(ctx context.Context, user *account.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *account.User
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, user interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, user *account.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*account.User))
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(_a0 error) *MockUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context.Context, *account.User) error) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLoginAttempt provides a mock function with given fields: ctx, id, failedCount, lockedUntil
func (_m *MockUserRepository) UpdateLoginAttempt(ctx context.Context, id string, failedCount int, lockedUntil *time.Time) error {
	ret := _m.Called(ctx, id, failedCount, lockedUntil)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLoginAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, *time.Time) error); ok {
		r0 = rf(ctx, id, failedCount, lockedUntil)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdateLoginAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLoginAttempt'
type MockUserRepository_UpdateLoginAttempt_Call struct {
	*mock.Call
}

// UpdateLoginAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - failedCount int
//   - lockedUntil *time.Time
func (_e *MockUserRepository_Expecter) UpdateLoginAttempt(ctx interface{}, id interface{}, failedCount interface{}, lockedUntil interface{}) *MockUserRepository_UpdateLoginAttempt_Call {
	return &MockUserRepository_UpdateLoginAttempt_Call{Call: _e.mock.On("UpdateLoginAttempt", ctx, id, failedCount, lockedUntil)}
}

func (_c *MockUserRepository_UpdateLoginAttempt_Call) Run(run func(ctx context.Context, id string, failedCount int, lockedUntil *time.Time)) *MockUserRepository_UpdateLoginAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(*time.Time))
	})
	return _c
}

func (_c *MockUserRepository_UpdateLoginAttempt_Call) Return(_a0 error) *MockUserRepository_UpdateLoginAttempt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdateLoginAttempt_Call) RunAndReturn(run func(context.Context, string, int, *time.Time) error) *MockUserRepository_UpdateLoginAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
