// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	account "github.com/aprxty3/your_persona_controller.git/internal/domain/account"

	mock "github.com/stretchr/testify/mock"
)

// MockReferralRepository is an autogenerated mock type for the ReferralRepository type
type MockReferralRepository struct {
	mock.Mock
}

type MockReferralRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReferralRepository) EXPECT() *MockReferralRepository_Expecter {
	return &MockReferralRepository_Expecter{mock: &_m.Mock}
}

// CountEventsByCodeID provides a mock function with given fields: ctx, referralCodeID, eventType
func (_m *MockReferralRepository) CountEventsByCodeID(ctx context.Context, referralCodeID string, eventType account.ReferralEventType) (int64, error) {
	ret := _m.Called(ctx, referralCodeID, eventType)

	if len(ret) == 0 {
		panic("no return value specified for CountEventsByCodeID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, account.ReferralEventType) (int64, error)); ok {
		return rf(ctx, referralCodeID, eventType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, account.ReferralEventType) int64); ok {
		r0 = rf(ctx, referralCodeID, eventType)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, account.ReferralEventType) error); ok {
		r1 = rf(ctx, referralCodeID, eventType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReferralRepository_CountEventsByCodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEventsByCodeID'
type MockReferralRepository_CountEventsByCodeID_Call struct {
	*mock.Call
}

// CountEventsByCodeID is a helper method to define mock.On call
//   - ctx context.Context
//   - referralCodeID string
//   - eventType account.ReferralEventType
func (_e *MockReferralRepository_Expecter) CountEventsByCodeID(ctx interface{}, referralCodeID interface{}, eventType interface{}) *MockReferralRepository_CountEventsByCodeID_Call {
	return &MockReferralRepository_CountEventsByCodeID_Call{Call: _e.mock.On("CountEventsByCodeID", ctx, referralCodeID, eventType)}
}

func (_c *MockReferralRepository_CountEventsByCodeID_Call) Run(run func(ctx context.Context, referralCodeID string, eventType account.ReferralEventType)) *MockReferralRepository_CountEventsByCodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(account.ReferralEventType))
	})
	return _c
}

func (_c *MockReferralRepository_CountEventsByCodeID_Call) Return(_a0 int64, _a1 error) *MockReferralRepository_CountEventsByCodeID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReferralRepository_CountEventsByCodeID_Call) RunAndReturn(run func(context.Context, string, account.ReferralEventType) (int64, error)) *MockReferralRepository_CountEventsByCodeID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCode provides a mock function with given fields: ctx, code
func (_m *MockReferralRepository) CreateCode(ctx context.Context, code *account.ReferralCode) error {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for CreateCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account.ReferralCode) error); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReferralRepository_CreateCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCode'
type MockReferralRepository_CreateCode_Call struct {
	*mock.Call
}

// CreateCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code *account.ReferralCode
func (_e *MockReferralRepository_Expecter) CreateCode(ctx interface{}, code interface{}) *MockReferralRepository_CreateCode_Call {
	return &MockReferralRepository_CreateCode_Call{Call: _e.mock.On("CreateCode", ctx, code)}
}

func (_c *MockReferralRepository_CreateCode_Call) Run(run func(ctx context.Context, code *account.ReferralCode)) *MockReferralRepository_CreateCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*account.ReferralCode))
	})
	return _c
}

func (_c *MockReferralRepository_CreateCode_Call) Return(_a0 error) *MockReferralRepository_CreateCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReferralRepository_CreateCode_Call) RunAndReturn(run func(context.Context, *account.ReferralCode) error) *MockReferralRepository_CreateCode_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvent provides a mock function with given fields: ctx, event
func (_m *MockReferralRepository) CreateEvent(ctx context.Context, event *account.ReferralEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account.ReferralEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReferralRepository_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockReferralRepository_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *account.ReferralEvent
func (_e *MockReferralRepository_Expecter) CreateEvent(ctx interface{}, event interface{}) *MockReferralRepository_CreateEvent_Call {
	return &MockReferralRepository_CreateEvent_Call{Call: _e.mock.On("CreateEvent", ctx, event)}
}

func (_c *MockReferralRepository_CreateEvent_Call) Run(run func(ctx context.Context, event *account.ReferralEvent)) *MockReferralRepository_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*account.ReferralEvent))
	})
	return _c
}

func (_c *MockReferralRepository_CreateEvent_Call) Return(_a0 error) *MockReferralRepository_CreateEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReferralRepository_CreateEvent_Call) RunAndReturn(run func(context.Context, *account.ReferralEvent) error) *MockReferralRepository_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// FindCodeByCode provides a mock function with given fields: ctx, code
func (_m *MockReferralRepository) FindCodeByCode(ctx context.Context, code string) (*account.ReferralCode, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindCodeByCode")
	}

	var r0 *account.ReferralCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*account.ReferralCode, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *account.ReferralCode); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ReferralCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReferralRepository_FindCodeByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCodeByCode'
type MockReferralRepository_FindCodeByCode_Call struct {
	*mock.Call
}

// FindCodeByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockReferralRepository_Expecter) FindCodeByCode(ctx interface{}, code interface{}) *MockReferralRepository_FindCodeByCode_Call {
	return &MockReferralRepository_FindCodeByCode_Call{Call: _e.mock.On("FindCodeByCode", ctx, code)}
}

func (_c *MockReferralRepository_FindCodeByCode_Call) Run(run func(ctx context.Context, code string)) *MockReferralRepository_FindCodeByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReferralRepository_FindCodeByCode_Call) Return(_a0 *account.ReferralCode, _a1 error) *MockReferralRepository_FindCodeByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReferralRepository_FindCodeByCode_Call) RunAndReturn(run func(context.Context, string) (*account.ReferralCode, error)) *MockReferralRepository_FindCodeByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindCodeByUserID provides a mock function with given fields: ctx, userID
func (_m *MockReferralRepository) FindCodeByUserID(ctx context.Context, userID string) (*account.ReferralCode, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindCodeByUserID")
	}

	var r0 *account.ReferralCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*account.ReferralCode, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *account.ReferralCode); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ReferralCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReferralRepository_FindCodeByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCodeByUserID'
type MockReferralRepository_FindCodeByUserID_Call struct {
	*mock.Call
}

// FindCodeByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockReferralRepository_Expecter) FindCodeByUserID(ctx interface{}, userID interface{}) *MockReferralRepository_FindCodeByUserID_Call {
	return &MockReferralRepository_FindCodeByUserID_Call{Call: _e.mock.On("FindCodeByUserID", ctx, userID)}
}

func (_c *MockReferralRepository_FindCodeByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockReferralRepository_FindCodeByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReferralRepository_FindCodeByUserID_Call) Return(_a0 *account.ReferralCode, _a1 error) *MockReferralRepository_FindCodeByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReferralRepository_FindCodeByUserID_Call) RunAndReturn(run func(context.Context, string) (*account.ReferralCode, error)) *MockReferralRepository_FindCodeByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReferralRepository creates a new instance of MockReferralRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReferralRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReferralRepository {
	mock := &MockReferralRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
