// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	account "github.com/aprxty3/your_persona_controller.git/internal/domain/account"

	mock "github.com/stretchr/testify/mock"
)

// MockVerificationTokenRepository is an autogenerated mock type for the VerificationTokenRepository type
type MockVerificationTokenRepository struct {
	mock.Mock
}

type MockVerificationTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerificationTokenRepository) EXPECT() *MockVerificationTokenRepository_Expecter {
	return &MockVerificationTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, token
func (_m *MockVerificationTokenRepository) Create(ctx context.Context, token *account.VerificationToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account.VerificationToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerificationTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVerificationTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *account.VerificationToken
func (_e *MockVerificationTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *MockVerificationTokenRepository_Create_Call {
	return &MockVerificationTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockVerificationTokenRepository_Create_Call) Run(run func(ctx context.Context, token *account.VerificationToken)) *MockVerificationTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*account.VerificationToken))
	})
	return _c
}

func (_c *MockVerificationTokenRepository_Create_Call) Return(_a0 error) *MockVerificationTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerificationTokenRepository_Create_Call) RunAndReturn(run func(context.Context, *account.VerificationToken) error) *MockVerificationTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExpireAllActiveForUser provides a mock function with given fields: ctx, userID, tokenType
func (_m *MockVerificationTokenRepository) ExpireAllActiveForUser(ctx context.Context, userID string, tokenType account.TokenType) error {
	ret := _m.Called(ctx, userID, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for ExpireAllActiveForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, account.TokenType) error); ok {
		r0 = rf(ctx, userID, tokenType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerificationTokenRepository_ExpireAllActiveForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireAllActiveForUser'
type MockVerificationTokenRepository_ExpireAllActiveForUser_Call struct {
	*mock.Call
}

// ExpireAllActiveForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tokenType account.TokenType
func (_e *MockVerificationTokenRepository_Expecter) ExpireAllActiveForUser(ctx interface{}, userID interface{}, tokenType interface{}) *MockVerificationTokenRepository_ExpireAllActiveForUser_Call {
	return &MockVerificationTokenRepository_ExpireAllActiveForUser_Call{Call: _e.mock.On("ExpireAllActiveForUser", ctx, userID, tokenType)}
}

func (_c *MockVerificationTokenRepository_ExpireAllActiveForUser_Call) Run(run func(ctx context.Context, userID string, tokenType account.TokenType)) *MockVerificationTokenRepository_ExpireAllActiveForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(account.TokenType))
	})
	return _c
}

func (_c *MockVerificationTokenRepository_ExpireAllActiveForUser_Call) Return(_a0 error) *MockVerificationTokenRepository_ExpireAllActiveForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerificationTokenRepository_ExpireAllActiveForUser_Call) RunAndReturn(run func(context.Context, string, account.TokenType) error) *MockVerificationTokenRepository_ExpireAllActiveForUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByUserAndType provides a mock function with given fields: ctx, userID, tokenType
func (_m *MockVerificationTokenRepository) FindActiveByUserAndType(ctx context.Context, userID string, tokenType account.TokenType) (*account.VerificationToken, error) {
	ret := _m.Called(ctx, userID, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByUserAndType")
	}

	var r0 *account.VerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, account.TokenType) (*account.VerificationToken, error)); ok {
		return rf(ctx, userID, tokenType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, account.TokenType) *account.VerificationToken); ok {
		r0 = rf(ctx, userID, tokenType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.VerificationToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, account.TokenType) error); ok {
		r1 = rf(ctx, userID, tokenType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVerificationTokenRepository_FindActiveByUserAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByUserAndType'
type MockVerificationTokenRepository_FindActiveByUserAndType_Call struct {
	*mock.Call
}

// FindActiveByUserAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tokenType account.TokenType
func (_e *MockVerificationTokenRepository_Expecter) FindActiveByUserAndType(ctx interface{}, userID interface{}, tokenType interface{}) *MockVerificationTokenRepository_FindActiveByUserAndType_Call {
	return &MockVerificationTokenRepository_FindActiveByUserAndType_Call{Call: _e.mock.On("FindActiveByUserAndType", ctx, userID, tokenType)}
}

func (_c *MockVerificationTokenRepository_FindActiveByUserAndType_Call) Run(run func(ctx context.Context, userID string, tokenType account.TokenType)) *MockVerificationTokenRepository_FindActiveByUserAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(account.TokenType))
	})
	return _c
}

func (_c *MockVerificationTokenRepository_FindActiveByUserAndType_Call) Return(_a0 *account.VerificationToken, _a1 error) *MockVerificationTokenRepository_FindActiveByUserAndType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVerificationTokenRepository_FindActiveByUserAndType_Call) RunAndReturn(run func(context.Context, string, account.TokenType) (*account.VerificationToken, error)) *MockVerificationTokenRepository_FindActiveByUserAndType_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementAttemptCount provides a mock function with given fields: ctx, tokenID
func (_m *MockVerificationTokenRepository) IncrementAttemptCount(ctx context.Context, tokenID string) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementAttemptCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerificationTokenRepository_IncrementAttemptCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementAttemptCount'
type MockVerificationTokenRepository_IncrementAttemptCount_Call struct {
	*mock.Call
}

// IncrementAttemptCount is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockVerificationTokenRepository_Expecter) IncrementAttemptCount(ctx interface{}, tokenID interface{}) *MockVerificationTokenRepository_IncrementAttemptCount_Call {
	return &MockVerificationTokenRepository_IncrementAttemptCount_Call{Call: _e.mock.On("IncrementAttemptCount", ctx, tokenID)}
}

func (_c *MockVerificationTokenRepository_IncrementAttemptCount_Call) Run(run func(ctx context.Context, tokenID string)) *MockVerificationTokenRepository_IncrementAttemptCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVerificationTokenRepository_IncrementAttemptCount_Call) Return(_a0 error) *MockVerificationTokenRepository_IncrementAttemptCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerificationTokenRepository_IncrementAttemptCount_Call) RunAndReturn(run func(context.Context, string) error) *MockVerificationTokenRepository_IncrementAttemptCount_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function with given fields: ctx, tokenID
func (_m *MockVerificationTokenRepository) MarkUsed(ctx context.Context, tokenID string) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerificationTokenRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockVerificationTokenRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockVerificationTokenRepository_Expecter) MarkUsed(ctx interface{}, tokenID interface{}) *MockVerificationTokenRepository_MarkUsed_Call {
	return &MockVerificationTokenRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, tokenID)}
}

func (_c *MockVerificationTokenRepository_MarkUsed_Call) Run(run func(ctx context.Context, tokenID string)) *MockVerificationTokenRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVerificationTokenRepository_MarkUsed_Call) Return(_a0 error) *MockVerificationTokenRepository_MarkUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerificationTokenRepository_MarkUsed_Call) RunAndReturn(run func(context.Context, string) error) *MockVerificationTokenRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerificationTokenRepository creates a new instance of MockVerificationTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerificationTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerificationTokenRepository {
	mock := &MockVerificationTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
