// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	account "github.com/aprxty3/your_persona_controller.git/internal/domain/account"

	mock "github.com/stretchr/testify/mock"
)

// MockGuestSessionRepository is an autogenerated mock type for the GuestSessionRepository type
type MockGuestSessionRepository struct {
	mock.Mock
}

type MockGuestSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGuestSessionRepository) EXPECT() *MockGuestSessionRepository_Expecter {
	return &MockGuestSessionRepository_Expecter{mock: &_m.Mock}
}

// AnonymizeClaimedByUser provides a mock function with given fields: ctx, userID
func (_m *MockGuestSessionRepository) AnonymizeClaimedByUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AnonymizeClaimedByUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGuestSessionRepository_AnonymizeClaimedByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnonymizeClaimedByUser'
type MockGuestSessionRepository_AnonymizeClaimedByUser_Call struct {
	*mock.Call
}

// AnonymizeClaimedByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockGuestSessionRepository_Expecter) AnonymizeClaimedByUser(ctx interface{}, userID interface{}) *MockGuestSessionRepository_AnonymizeClaimedByUser_Call {
	return &MockGuestSessionRepository_AnonymizeClaimedByUser_Call{Call: _e.mock.On("AnonymizeClaimedByUser", ctx, userID)}
}

func (_c *MockGuestSessionRepository_AnonymizeClaimedByUser_Call) Run(run func(ctx context.Context, userID string)) *MockGuestSessionRepository_AnonymizeClaimedByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGuestSessionRepository_AnonymizeClaimedByUser_Call) Return(_a0 error) *MockGuestSessionRepository_AnonymizeClaimedByUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGuestSessionRepository_AnonymizeClaimedByUser_Call) RunAndReturn(run func(context.Context, string) error) *MockGuestSessionRepository_AnonymizeClaimedByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, session
func (_m *MockGuestSessionRepository) Create(ctx context.Context, session *account.GuestSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account.GuestSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGuestSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGuestSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *account.GuestSession
func (_e *MockGuestSessionRepository_Expecter) Create(ctx interface{}, session interface{}) *MockGuestSessionRepository_Create_Call {
	return &MockGuestSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockGuestSessionRepository_Create_Call) Run(run func(ctx context.Context, session *account.GuestSession)) *MockGuestSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*account.GuestSession))
	})
	return _c
}

func (_c *MockGuestSessionRepository_Create_Call) Return(_a0 error) *MockGuestSessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGuestSessionRepository_Create_Call) RunAndReturn(run func(context.Context, *account.GuestSession) error) *MockGuestSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *MockGuestSessionRepository) DeleteBySessionID(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBySessionID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGuestSessionRepository_DeleteBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBySessionID'
type MockGuestSessionRepository_DeleteBySessionID_Call struct {
	*mock.Call
}

// DeleteBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockGuestSessionRepository_Expecter) DeleteBySessionID(ctx interface{}, sessionID interface{}) *MockGuestSessionRepository_DeleteBySessionID_Call {
	return &MockGuestSessionRepository_DeleteBySessionID_Call{Call: _e.mock.On("DeleteBySessionID", ctx, sessionID)}
}

func (_c *MockGuestSessionRepository_DeleteBySessionID_Call) Run(run func(ctx context.Context, sessionID string)) *MockGuestSessionRepository_DeleteBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGuestSessionRepository_DeleteBySessionID_Call) Return(_a0 error) *MockGuestSessionRepository_DeleteBySessionID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGuestSessionRepository_DeleteBySessionID_Call) RunAndReturn(run func(context.Context, string) error) *MockGuestSessionRepository_DeleteBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *MockGuestSessionRepository) FindBySessionID(ctx context.Context, sessionID string) (*account.GuestSession, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySessionID")
	}

	var r0 *account.GuestSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*account.GuestSession, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *account.GuestSession); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.GuestSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGuestSessionRepository_FindBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySessionID'
type MockGuestSessionRepository_FindBySessionID_Call struct {
	*mock.Call
}

// FindBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockGuestSessionRepository_Expecter) FindBySessionID(ctx interface{}, sessionID interface{}) *MockGuestSessionRepository_FindBySessionID_Call {
	return &MockGuestSessionRepository_FindBySessionID_Call{Call: _e.mock.On("FindBySessionID", ctx, sessionID)}
}

func (_c *MockGuestSessionRepository_FindBySessionID_Call) Run(run func(ctx context.Context, sessionID string)) *MockGuestSessionRepository_FindBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGuestSessionRepository_FindBySessionID_Call) Return(_a0 *account.GuestSession, _a1 error) *MockGuestSessionRepository_FindBySessionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGuestSessionRepository_FindBySessionID_Call) RunAndReturn(run func(context.Context, string) (*account.GuestSession, error)) *MockGuestSessionRepository_FindBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// FindExpiredUnclaimed provides a mock function with given fields: ctx
func (_m *MockGuestSessionRepository) FindExpiredUnclaimed(ctx context.Context) ([]account.GuestSession, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiredUnclaimed")
	}

	var r0 []account.GuestSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]account.GuestSession, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []account.GuestSession); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]account.GuestSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGuestSessionRepository_FindExpiredUnclaimed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindExpiredUnclaimed'
type MockGuestSessionRepository_FindExpiredUnclaimed_Call struct {
	*mock.Call
}

// FindExpiredUnclaimed is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGuestSessionRepository_Expecter) FindExpiredUnclaimed(ctx interface{}) *MockGuestSessionRepository_FindExpiredUnclaimed_Call {
	return &MockGuestSessionRepository_FindExpiredUnclaimed_Call{Call: _e.mock.On("FindExpiredUnclaimed", ctx)}
}

func (_c *MockGuestSessionRepository_FindExpiredUnclaimed_Call) Run(run func(ctx context.Context)) *MockGuestSessionRepository_FindExpiredUnclaimed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGuestSessionRepository_FindExpiredUnclaimed_Call) Return(_a0 []account.GuestSession, _a1 error) *MockGuestSessionRepository_FindExpiredUnclaimed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGuestSessionRepository_FindExpiredUnclaimed_Call) RunAndReturn(run func(context.Context) ([]account.GuestSession, error)) *MockGuestSessionRepository_FindExpiredUnclaimed_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, session
func (_m *MockGuestSessionRepository) Update(ctx context.Context, session *account.GuestSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account.GuestSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGuestSessionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGuestSessionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - session *account.GuestSession
func (_e *MockGuestSessionRepository_Expecter) Update(ctx interface{}, session interface{}) *MockGuestSessionRepository_Update_Call {
	return &MockGuestSessionRepository_Update_Call{Call: _e.mock.On("Update", ctx, session)}
}

func (_c *MockGuestSessionRepository_Update_Call) Run(run func(ctx context.Context, session *account.GuestSession)) *MockGuestSessionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*account.GuestSession))
	})
	return _c
}

func (_c *MockGuestSessionRepository_Update_Call) Return(_a0 error) *MockGuestSessionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGuestSessionRepository_Update_Call) RunAndReturn(run func(context.Context, *account.GuestSession) error) *MockGuestSessionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGuestSessionRepository creates a new instance of MockGuestSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGuestSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGuestSessionRepository {
	mock := &MockGuestSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
