// Code generated by mockery v2.53.6. DO NOT EDIT.

package assessment

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockPDFSignerService is an autogenerated mock type for the PDFSignerService type
type MockPDFSignerService struct {
	mock.Mock
}

type MockPDFSignerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPDFSignerService) EXPECT() *MockPDFSignerService_Expecter {
	return &MockPDFSignerService_Expecter{mock: &_m.Mock}
}

// PresignedGetURL provides a mock function with given fields: ctx, objectURL, expiry
func (_m *MockPDFSignerService) PresignedGetURL(ctx context.Context, objectURL string, expiry time.Duration) (string, error) {
	ret := _m.Called(ctx, objectURL, expiry)

	if len(ret) == 0 {
		panic("no return value specified for PresignedGetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, objectURL, expiry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, objectURL, expiry)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, objectURL, expiry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPDFSignerService_PresignedGetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignedGetURL'
type MockPDFSignerService_PresignedGetURL_Call struct {
	*mock.Call
}

// PresignedGetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - objectURL string
//   - expiry time.Duration
func (_e *MockPDFSignerService_Expecter) PresignedGetURL(ctx interface{}, objectURL interface{}, expiry interface{}) *MockPDFSignerService_PresignedGetURL_Call {
	return &MockPDFSignerService_PresignedGetURL_Call{Call: _e.mock.On("PresignedGetURL", ctx, objectURL, expiry)}
}

func (_c *MockPDFSignerService_PresignedGetURL_Call) Run(run func(ctx context.Context, objectURL string, expiry time.Duration)) *MockPDFSignerService_PresignedGetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockPDFSignerService_PresignedGetURL_Call) Return(_a0 string, _a1 error) *MockPDFSignerService_PresignedGetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPDFSignerService_PresignedGetURL_Call) RunAndReturn(run func(context.Context, string, time.Duration) (string, error)) *MockPDFSignerService_PresignedGetURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPDFSignerService creates a new instance of MockPDFSignerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPDFSignerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPDFSignerService {
	mock := &MockPDFSignerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
