// Code generated by mockery v2.53.6. DO NOT EDIT.

package assessment

import (
	context "context"

	content "github.com/aprxty3/your_persona_controller.git/internal/domain/content"

	mock "github.com/stretchr/testify/mock"
)

// MockQuestionCatalogRepository is an autogenerated mock type for the QuestionCatalogRepository type
type MockQuestionCatalogRepository struct {
	mock.Mock
}

type MockQuestionCatalogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuestionCatalogRepository) EXPECT() *MockQuestionCatalogRepository_Expecter {
	return &MockQuestionCatalogRepository_Expecter{mock: &_m.Mock}
}

// FindAllWithTranslation provides a mock function with given fields: ctx, locale
func (_m *MockQuestionCatalogRepository) FindAllWithTranslation(ctx context.Context, locale string) ([]content.Question, map[string]content.QuestionTranslation, error) {
	ret := _m.Called(ctx, locale)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithTranslation")
	}

	var r0 []content.Question
	var r1 map[string]content.QuestionTranslation
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]content.Question, map[string]content.QuestionTranslation, error)); ok {
		return rf(ctx, locale)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []content.Question); ok {
		r0 = rf(ctx, locale)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]content.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) map[string]content.QuestionTranslation); ok {
		r1 = rf(ctx, locale)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]content.QuestionTranslation)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, locale)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockQuestionCatalogRepository_FindAllWithTranslation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllWithTranslation'
type MockQuestionCatalogRepository_FindAllWithTranslation_Call struct {
	*mock.Call
}

// FindAllWithTranslation is a helper method to define mock.On call
//   - ctx context.Context
//   - locale string
func (_e *MockQuestionCatalogRepository_Expecter) FindAllWithTranslation(ctx interface{}, locale interface{}) *MockQuestionCatalogRepository_FindAllWithTranslation_Call {
	return &MockQuestionCatalogRepository_FindAllWithTranslation_Call{Call: _e.mock.On("FindAllWithTranslation", ctx, locale)}
}

func (_c *MockQuestionCatalogRepository_FindAllWithTranslation_Call) Run(run func(ctx context.Context, locale string)) *MockQuestionCatalogRepository_FindAllWithTranslation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuestionCatalogRepository_FindAllWithTranslation_Call) Return(_a0 []content.Question, _a1 map[string]content.QuestionTranslation, _a2 error) *MockQuestionCatalogRepository_FindAllWithTranslation_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockQuestionCatalogRepository_FindAllWithTranslation_Call) RunAndReturn(run func(context.Context, string) ([]content.Question, map[string]content.QuestionTranslation, error)) *MockQuestionCatalogRepository_FindAllWithTranslation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuestionCatalogRepository creates a new instance of MockQuestionCatalogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuestionCatalogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuestionCatalogRepository {
	mock := &MockQuestionCatalogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
