// Code generated by mockery v2.53.6. DO NOT EDIT.

package assessment

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockIdempotencyService is an autogenerated mock type for the IdempotencyService type
type MockIdempotencyService struct {
	mock.Mock
}

type MockIdempotencyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdempotencyService) EXPECT() *MockIdempotencyService_Expecter {
	return &MockIdempotencyService_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: ctx, key, payloadHash
func (_m *MockIdempotencyService) Check(ctx context.Context, key string, payloadHash string) (*SubmitResponse, error) {
	ret := _m.Called(ctx, key, payloadHash)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 *SubmitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*SubmitResponse, error)); ok {
		return rf(ctx, key, payloadHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *SubmitResponse); ok {
		r0 = rf(ctx, key, payloadHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SubmitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, payloadHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdempotencyService_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockIdempotencyService_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - payloadHash string
func (_e *MockIdempotencyService_Expecter) Check(ctx interface{}, key interface{}, payloadHash interface{}) *MockIdempotencyService_Check_Call {
	return &MockIdempotencyService_Check_Call{Call: _e.mock.On("Check", ctx, key, payloadHash)}
}

func (_c *MockIdempotencyService_Check_Call) Run(run func(ctx context.Context, key string, payloadHash string)) *MockIdempotencyService_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIdempotencyService_Check_Call) Return(_a0 *SubmitResponse, _a1 error) *MockIdempotencyService_Check_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdempotencyService_Check_Call) RunAndReturn(run func(context.Context, string, string) (*SubmitResponse, error)) *MockIdempotencyService_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, key, payloadHash, response, ttl
func (_m *MockIdempotencyService) Save(ctx context.Context, key string, payloadHash string, response *SubmitResponse, ttl time.Duration) error {
	ret := _m.Called(ctx, key, payloadHash, response, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *SubmitResponse, time.Duration) error); ok {
		r0 = rf(ctx, key, payloadHash, response, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIdempotencyService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIdempotencyService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - payloadHash string
//   - response *SubmitResponse
//   - ttl time.Duration
func (_e *MockIdempotencyService_Expecter) Save(ctx interface{}, key interface{}, payloadHash interface{}, response interface{}, ttl interface{}) *MockIdempotencyService_Save_Call {
	return &MockIdempotencyService_Save_Call{Call: _e.mock.On("Save", ctx, key, payloadHash, response, ttl)}
}

func (_c *MockIdempotencyService_Save_Call) Run(run func(ctx context.Context, key string, payloadHash string, response *SubmitResponse, ttl time.Duration)) *MockIdempotencyService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*SubmitResponse), args[4].(time.Duration))
	})
	return _c
}

func (_c *MockIdempotencyService_Save_Call) Return(_a0 error) *MockIdempotencyService_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdempotencyService_Save_Call) RunAndReturn(run func(context.Context, string, string, *SubmitResponse, time.Duration) error) *MockIdempotencyService_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdempotencyService creates a new instance of MockIdempotencyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdempotencyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdempotencyService {
	mock := &MockIdempotencyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
