// Code generated by mockery v2.53.6. DO NOT EDIT.

package assessment

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockDistributedLockService is an autogenerated mock type for the DistributedLockService type
type MockDistributedLockService struct {
	mock.Mock
}

type MockDistributedLockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDistributedLockService) EXPECT() *MockDistributedLockService_Expecter {
	return &MockDistributedLockService_Expecter{mock: &_m.Mock}
}

// AcquireLock provides a mock function with given fields: ctx, key, ttl
func (_m *MockDistributedLockService) AcquireLock(ctx context.Context, key string, ttl time.Duration) (bool, error) {
	ret := _m.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for AcquireLock")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (bool, error)); ok {
		return rf(ctx, key, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) bool); ok {
		r0 = rf(ctx, key, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, key, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDistributedLockService_AcquireLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireLock'
type MockDistributedLockService_AcquireLock_Call struct {
	*mock.Call
}

// AcquireLock is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
func (_e *MockDistributedLockService_Expecter) AcquireLock(ctx interface{}, key interface{}, ttl interface{}) *MockDistributedLockService_AcquireLock_Call {
	return &MockDistributedLockService_AcquireLock_Call{Call: _e.mock.On("AcquireLock", ctx, key, ttl)}
}

func (_c *MockDistributedLockService_AcquireLock_Call) Run(run func(ctx context.Context, key string, ttl time.Duration)) *MockDistributedLockService_AcquireLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockDistributedLockService_AcquireLock_Call) Return(_a0 bool, _a1 error) *MockDistributedLockService_AcquireLock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDistributedLockService_AcquireLock_Call) RunAndReturn(run func(context.Context, string, time.Duration) (bool, error)) *MockDistributedLockService_AcquireLock_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseLock provides a mock function with given fields: ctx, key
func (_m *MockDistributedLockService) ReleaseLock(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDistributedLockService_ReleaseLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseLock'
type MockDistributedLockService_ReleaseLock_Call struct {
	*mock.Call
}

// ReleaseLock is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockDistributedLockService_Expecter) ReleaseLock(ctx interface{}, key interface{}) *MockDistributedLockService_ReleaseLock_Call {
	return &MockDistributedLockService_ReleaseLock_Call{Call: _e.mock.On("ReleaseLock", ctx, key)}
}

func (_c *MockDistributedLockService_ReleaseLock_Call) Run(run func(ctx context.Context, key string)) *MockDistributedLockService_ReleaseLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDistributedLockService_ReleaseLock_Call) Return(_a0 error) *MockDistributedLockService_ReleaseLock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDistributedLockService_ReleaseLock_Call) RunAndReturn(run func(context.Context, string) error) *MockDistributedLockService_ReleaseLock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDistributedLockService creates a new instance of MockDistributedLockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDistributedLockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDistributedLockService {
	mock := &MockDistributedLockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
