// Code generated by mockery v2.53.6. DO NOT EDIT.

package assessment

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTestResultRepository is an autogenerated mock type for the TestResultRepository type
type MockTestResultRepository struct {
	mock.Mock
}

type MockTestResultRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestResultRepository) EXPECT() *MockTestResultRepository_Expecter {
	return &MockTestResultRepository_Expecter{mock: &_m.Mock}
}

// CountCompletedByUser provides a mock function with given fields: ctx, userID
func (_m *MockTestResultRepository) CountCompletedByUser(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountCompletedByUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestResultRepository_CountCompletedByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountCompletedByUser'
type MockTestResultRepository_CountCompletedByUser_Call struct {
	*mock.Call
}

// CountCompletedByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTestResultRepository_Expecter) CountCompletedByUser(ctx interface{}, userID interface{}) *MockTestResultRepository_CountCompletedByUser_Call {
	return &MockTestResultRepository_CountCompletedByUser_Call{Call: _e.mock.On("CountCompletedByUser", ctx, userID)}
}

func (_c *MockTestResultRepository_CountCompletedByUser_Call) Run(run func(ctx context.Context, userID string)) *MockTestResultRepository_CountCompletedByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_CountCompletedByUser_Call) Return(_a0 int64, _a1 error) *MockTestResultRepository_CountCompletedByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestResultRepository_CountCompletedByUser_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockTestResultRepository_CountCompletedByUser_Call {
	_c.Call.Return(run)
	return _c
}

// CountMonthlyUsage provides a mock function with given fields: ctx, userID
func (_m *MockTestResultRepository) CountMonthlyUsage(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountMonthlyUsage")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestResultRepository_CountMonthlyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountMonthlyUsage'
type MockTestResultRepository_CountMonthlyUsage_Call struct {
	*mock.Call
}

// CountMonthlyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTestResultRepository_Expecter) CountMonthlyUsage(ctx interface{}, userID interface{}) *MockTestResultRepository_CountMonthlyUsage_Call {
	return &MockTestResultRepository_CountMonthlyUsage_Call{Call: _e.mock.On("CountMonthlyUsage", ctx, userID)}
}

func (_c *MockTestResultRepository_CountMonthlyUsage_Call) Run(run func(ctx context.Context, userID string)) *MockTestResultRepository_CountMonthlyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_CountMonthlyUsage_Call) Return(_a0 int64, _a1 error) *MockTestResultRepository_CountMonthlyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestResultRepository_CountMonthlyUsage_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockTestResultRepository_CountMonthlyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// CountMonthlyUsageByGuestSession provides a mock function with given fields: ctx, guestSessionID
func (_m *MockTestResultRepository) CountMonthlyUsageByGuestSession(ctx context.Context, guestSessionID string) (int64, error) {
	ret := _m.Called(ctx, guestSessionID)

	if len(ret) == 0 {
		panic("no return value specified for CountMonthlyUsageByGuestSession")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, guestSessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, guestSessionID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, guestSessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestResultRepository_CountMonthlyUsageByGuestSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountMonthlyUsageByGuestSession'
type MockTestResultRepository_CountMonthlyUsageByGuestSession_Call struct {
	*mock.Call
}

// CountMonthlyUsageByGuestSession is a helper method to define mock.On call
//   - ctx context.Context
//   - guestSessionID string
func (_e *MockTestResultRepository_Expecter) CountMonthlyUsageByGuestSession(ctx interface{}, guestSessionID interface{}) *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call {
	return &MockTestResultRepository_CountMonthlyUsageByGuestSession_Call{Call: _e.mock.On("CountMonthlyUsageByGuestSession", ctx, guestSessionID)}
}

func (_c *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call) Run(run func(ctx context.Context, guestSessionID string)) *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call) Return(_a0 int64, _a1 error) *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTestResultRepository creates a new instance of MockTestResultRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestResultRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestResultRepository {
	mock := &MockTestResultRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
