// Code generated by mockery v2.53.6. DO NOT EDIT.

package assessment

import (
	context "context"

	testresult "github.com/aprxty3/your_persona_controller.git/internal/domain/testresult"
	mock "github.com/stretchr/testify/mock"
)

// MockResultRepository is an autogenerated mock type for the ResultRepository type
type MockResultRepository struct {
	mock.Mock
}

type MockResultRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResultRepository) EXPECT() *MockResultRepository_Expecter {
	return &MockResultRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockResultRepository) FindByID(ctx context.Context, id string) (*testresult.TestResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *testresult.TestResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*testresult.TestResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *testresult.TestResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*testresult.TestResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResultRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockResultRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockResultRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockResultRepository_FindByID_Call {
	return &MockResultRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockResultRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockResultRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockResultRepository_FindByID_Call) Return(_a0 *testresult.TestResult, _a1 error) *MockResultRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResultRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*testresult.TestResult, error)) *MockResultRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, result
func (_m *MockResultRepository) Update(ctx context.Context, result *testresult.TestResult) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *testresult.TestResult) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockResultRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockResultRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - result *testresult.TestResult
func (_e *MockResultRepository_Expecter) Update(ctx interface{}, result interface{}) *MockResultRepository_Update_Call {
	return &MockResultRepository_Update_Call{Call: _e.mock.On("Update", ctx, result)}
}

func (_c *MockResultRepository_Update_Call) Run(run func(ctx context.Context, result *testresult.TestResult)) *MockResultRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*testresult.TestResult))
	})
	return _c
}

func (_c *MockResultRepository_Update_Call) Return(_a0 error) *MockResultRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResultRepository_Update_Call) RunAndReturn(run func(context.Context, *testresult.TestResult) error) *MockResultRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResultRepository creates a new instance of MockResultRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResultRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResultRepository {
	mock := &MockResultRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
