// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/aprxty3/your_persona_controller.git/internal/application/pdf/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockRenderer is an autogenerated mock type for the Renderer type
type MockRenderer struct {
	mock.Mock
}

type MockRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRenderer) EXPECT() *MockRenderer_Expecter {
	return &MockRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function with given fields: ctx, data
func (_m *MockRenderer) Render(ctx context.Context, data dto.PDFData) ([]byte, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.PDFData) ([]byte, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.PDFData) []byte); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.PDFData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - ctx context.Context
//   - data dto.PDFData
func (_e *MockRenderer_Expecter) Render(ctx interface{}, data interface{}) *MockRenderer_Render_Call {
	return &MockRenderer_Render_Call{Call: _e.mock.On("Render", ctx, data)}
}

func (_c *MockRenderer_Render_Call) Run(run func(ctx context.Context, data dto.PDFData)) *MockRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.PDFData))
	})
	return _c
}

func (_c *MockRenderer_Render_Call) Return(_a0 []byte, _a1 error) *MockRenderer_Render_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRenderer_Render_Call) RunAndReturn(run func(context.Context, dto.PDFData) ([]byte, error)) *MockRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRenderer creates a new instance of MockRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRenderer {
	mock := &MockRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
