// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMailer is an autogenerated mock type for the Mailer type
type MockMailer struct {
	mock.Mock
}

type MockMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailer) EXPECT() *MockMailer_Expecter {
	return &MockMailer_Expecter{mock: &_m.Mock}
}

// SendDeletionConfirmed provides a mock function with given fields: ctx, to, locale
func (_m *MockMailer) SendDeletionConfirmed(ctx context.Context, to string, locale string) error {
	ret := _m.Called(ctx, to, locale)

	if len(ret) == 0 {
		panic("no return value specified for SendDeletionConfirmed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, to, locale)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailer_SendDeletionConfirmed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDeletionConfirmed'
type MockMailer_SendDeletionConfirmed_Call struct {
	*mock.Call
}

// SendDeletionConfirmed is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - locale string
func (_e *MockMailer_Expecter) SendDeletionConfirmed(ctx interface{}, to interface{}, locale interface{}) *MockMailer_SendDeletionConfirmed_Call {
	return &MockMailer_SendDeletionConfirmed_Call{Call: _e.mock.On("SendDeletionConfirmed", ctx, to, locale)}
}

func (_c *MockMailer_SendDeletionConfirmed_Call) Run(run func(ctx context.Context, to string, locale string)) *MockMailer_SendDeletionConfirmed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMailer_SendDeletionConfirmed_Call) Return(_a0 error) *MockMailer_SendDeletionConfirmed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailer_SendDeletionConfirmed_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMailer_SendDeletionConfirmed_Call {
	_c.Call.Return(run)
	return _c
}

// SendEmail provides a mock function with given fields: ctx, to, subject, body
func (_m *MockMailer) SendEmail(ctx context.Context, to string, subject string, body string) error {
	ret := _m.Called(ctx, to, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, to, subject, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailer_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MockMailer_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - subject string
//   - body string
func (_e *MockMailer_Expecter) SendEmail(ctx interface{}, to interface{}, subject interface{}, body interface{}) *MockMailer_SendEmail_Call {
	return &MockMailer_SendEmail_Call{Call: _e.mock.On("SendEmail", ctx, to, subject, body)}
}

func (_c *MockMailer_SendEmail_Call) Run(run func(ctx context.Context, to string, subject string, body string)) *MockMailer_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockMailer_SendEmail_Call) Return(_a0 error) *MockMailer_SendEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailer_SendEmail_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockMailer_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendOTP provides a mock function with given fields: ctx, to, otp, purpose, locale
func (_m *MockMailer) SendOTP(ctx context.Context, to string, otp string, purpose string, locale string) error {
	ret := _m.Called(ctx, to, otp, purpose, locale)

	if len(ret) == 0 {
		panic("no return value specified for SendOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, to, otp, purpose, locale)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailer_SendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOTP'
type MockMailer_SendOTP_Call struct {
	*mock.Call
}

// SendOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - otp string
//   - purpose string
//   - locale string
func (_e *MockMailer_Expecter) SendOTP(ctx interface{}, to interface{}, otp interface{}, purpose interface{}, locale interface{}) *MockMailer_SendOTP_Call {
	return &MockMailer_SendOTP_Call{Call: _e.mock.On("SendOTP", ctx, to, otp, purpose, locale)}
}

func (_c *MockMailer_SendOTP_Call) Run(run func(ctx context.Context, to string, otp string, purpose string, locale string)) *MockMailer_SendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockMailer_SendOTP_Call) Return(_a0 error) *MockMailer_SendOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailer_SendOTP_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MockMailer_SendOTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMailer creates a new instance of MockMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailer {
	mock := &MockMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
