// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	testresult "github.com/aprxty3/your_persona_controller.git/internal/domain/testresult"
	mock "github.com/stretchr/testify/mock"
)

// MockAnswerRepository is an autogenerated mock type for the AnswerRepository type
type MockAnswerRepository struct {
	mock.Mock
}

type MockAnswerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnswerRepository) EXPECT() *MockAnswerRepository_Expecter {
	return &MockAnswerRepository_Expecter{mock: &_m.Mock}
}

// DeleteByTestResultID provides a mock function with given fields: ctx, testResultID
func (_m *MockAnswerRepository) DeleteByTestResultID(ctx context.Context, testResultID string) error {
	ret := _m.Called(ctx, testResultID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTestResultID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, testResultID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnswerRepository_DeleteByTestResultID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByTestResultID'
type MockAnswerRepository_DeleteByTestResultID_Call struct {
	*mock.Call
}

// DeleteByTestResultID is a helper method to define mock.On call
//   - ctx context.Context
//   - testResultID string
func (_e *MockAnswerRepository_Expecter) DeleteByTestResultID(ctx interface{}, testResultID interface{}) *MockAnswerRepository_DeleteByTestResultID_Call {
	return &MockAnswerRepository_DeleteByTestResultID_Call{Call: _e.mock.On("DeleteByTestResultID", ctx, testResultID)}
}

func (_c *MockAnswerRepository_DeleteByTestResultID_Call) Run(run func(ctx context.Context, testResultID string)) *MockAnswerRepository_DeleteByTestResultID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAnswerRepository_DeleteByTestResultID_Call) Return(_a0 error) *MockAnswerRepository_DeleteByTestResultID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnswerRepository_DeleteByTestResultID_Call) RunAndReturn(run func(context.Context, string) error) *MockAnswerRepository_DeleteByTestResultID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTestResultID provides a mock function with given fields: ctx, testResultID
func (_m *MockAnswerRepository) FindByTestResultID(ctx context.Context, testResultID string) ([]testresult.Answer, error) {
	ret := _m.Called(ctx, testResultID)

	if len(ret) == 0 {
		panic("no return value specified for FindByTestResultID")
	}

	var r0 []testresult.Answer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]testresult.Answer, error)); ok {
		return rf(ctx, testResultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []testresult.Answer); ok {
		r0 = rf(ctx, testResultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]testresult.Answer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, testResultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnswerRepository_FindByTestResultID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTestResultID'
type MockAnswerRepository_FindByTestResultID_Call struct {
	*mock.Call
}

// FindByTestResultID is a helper method to define mock.On call
//   - ctx context.Context
//   - testResultID string
func (_e *MockAnswerRepository_Expecter) FindByTestResultID(ctx interface{}, testResultID interface{}) *MockAnswerRepository_FindByTestResultID_Call {
	return &MockAnswerRepository_FindByTestResultID_Call{Call: _e.mock.On("FindByTestResultID", ctx, testResultID)}
}

func (_c *MockAnswerRepository_FindByTestResultID_Call) Run(run func(ctx context.Context, testResultID string)) *MockAnswerRepository_FindByTestResultID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAnswerRepository_FindByTestResultID_Call) Return(_a0 []testresult.Answer, _a1 error) *MockAnswerRepository_FindByTestResultID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnswerRepository_FindByTestResultID_Call) RunAndReturn(run func(context.Context, string) ([]testresult.Answer, error)) *MockAnswerRepository_FindByTestResultID_Call {
	_c.Call.Return(run)
	return _c
}

// ScrubEssayAnswersByUser provides a mock function with given fields: ctx, userID
func (_m *MockAnswerRepository) ScrubEssayAnswersByUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ScrubEssayAnswersByUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnswerRepository_ScrubEssayAnswersByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScrubEssayAnswersByUser'
type MockAnswerRepository_ScrubEssayAnswersByUser_Call struct {
	*mock.Call
}

// ScrubEssayAnswersByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAnswerRepository_Expecter) ScrubEssayAnswersByUser(ctx interface{}, userID interface{}) *MockAnswerRepository_ScrubEssayAnswersByUser_Call {
	return &MockAnswerRepository_ScrubEssayAnswersByUser_Call{Call: _e.mock.On("ScrubEssayAnswersByUser", ctx, userID)}
}

func (_c *MockAnswerRepository_ScrubEssayAnswersByUser_Call) Run(run func(ctx context.Context, userID string)) *MockAnswerRepository_ScrubEssayAnswersByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAnswerRepository_ScrubEssayAnswersByUser_Call) Return(_a0 error) *MockAnswerRepository_ScrubEssayAnswersByUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnswerRepository_ScrubEssayAnswersByUser_Call) RunAndReturn(run func(context.Context, string) error) *MockAnswerRepository_ScrubEssayAnswersByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAnswers provides a mock function with given fields: ctx, testResultID, answers
func (_m *MockAnswerRepository) UpsertAnswers(ctx context.Context, testResultID string, answers []testresult.Answer) error {
	ret := _m.Called(ctx, testResultID, answers)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAnswers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []testresult.Answer) error); ok {
		r0 = rf(ctx, testResultID, answers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnswerRepository_UpsertAnswers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAnswers'
type MockAnswerRepository_UpsertAnswers_Call struct {
	*mock.Call
}

// UpsertAnswers is a helper method to define mock.On call
//   - ctx context.Context
//   - testResultID string
//   - answers []testresult.Answer
func (_e *MockAnswerRepository_Expecter) UpsertAnswers(ctx interface{}, testResultID interface{}, answers interface{}) *MockAnswerRepository_UpsertAnswers_Call {
	return &MockAnswerRepository_UpsertAnswers_Call{Call: _e.mock.On("UpsertAnswers", ctx, testResultID, answers)}
}

func (_c *MockAnswerRepository_UpsertAnswers_Call) Run(run func(ctx context.Context, testResultID string, answers []testresult.Answer)) *MockAnswerRepository_UpsertAnswers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]testresult.Answer))
	})
	return _c
}

func (_c *MockAnswerRepository_UpsertAnswers_Call) Return(_a0 error) *MockAnswerRepository_UpsertAnswers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnswerRepository_UpsertAnswers_Call) RunAndReturn(run func(context.Context, string, []testresult.Answer) error) *MockAnswerRepository_UpsertAnswers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnswerRepository creates a new instance of MockAnswerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnswerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnswerRepository {
	mock := &MockAnswerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
