// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	testresult "github.com/aprxty3/your_persona_controller.git/internal/domain/testresult"
	mock "github.com/stretchr/testify/mock"
)

// MockTestResultRepository is an autogenerated mock type for the TestResultRepository type
type MockTestResultRepository struct {
	mock.Mock
}

type MockTestResultRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestResultRepository) EXPECT() *MockTestResultRepository_Expecter {
	return &MockTestResultRepository_Expecter{mock: &_m.Mock}
}

// CountCompletedByGuestSession provides a mock function with given fields: ctx, guestSessionID
func (_m *MockTestResultRepository) CountCompletedByGuestSession(ctx context.Context, guestSessionID string) (int64, error) {
	ret := _m.Called(ctx, guestSessionID)

	if len(ret) == 0 {
		panic("no return value specified for CountCompletedByGuestSession")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, guestSessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, guestSessionID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, guestSessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestResultRepository_CountCompletedByGuestSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountCompletedByGuestSession'
type MockTestResultRepository_CountCompletedByGuestSession_Call struct {
	*mock.Call
}

// CountCompletedByGuestSession is a helper method to define mock.On call
//   - ctx context.Context
//   - guestSessionID string
func (_e *MockTestResultRepository_Expecter) CountCompletedByGuestSession(ctx interface{}, guestSessionID interface{}) *MockTestResultRepository_CountCompletedByGuestSession_Call {
	return &MockTestResultRepository_CountCompletedByGuestSession_Call{Call: _e.mock.On("CountCompletedByGuestSession", ctx, guestSessionID)}
}

func (_c *MockTestResultRepository_CountCompletedByGuestSession_Call) Run(run func(ctx context.Context, guestSessionID string)) *MockTestResultRepository_CountCompletedByGuestSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_CountCompletedByGuestSession_Call) Return(_a0 int64, _a1 error) *MockTestResultRepository_CountCompletedByGuestSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestResultRepository_CountCompletedByGuestSession_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockTestResultRepository_CountCompletedByGuestSession_Call {
	_c.Call.Return(run)
	return _c
}

// CountCompletedByUser provides a mock function with given fields: ctx, userID
func (_m *MockTestResultRepository) CountCompletedByUser(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountCompletedByUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestResultRepository_CountCompletedByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountCompletedByUser'
type MockTestResultRepository_CountCompletedByUser_Call struct {
	*mock.Call
}

// CountCompletedByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTestResultRepository_Expecter) CountCompletedByUser(ctx interface{}, userID interface{}) *MockTestResultRepository_CountCompletedByUser_Call {
	return &MockTestResultRepository_CountCompletedByUser_Call{Call: _e.mock.On("CountCompletedByUser", ctx, userID)}
}

func (_c *MockTestResultRepository_CountCompletedByUser_Call) Run(run func(ctx context.Context, userID string)) *MockTestResultRepository_CountCompletedByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_CountCompletedByUser_Call) Return(_a0 int64, _a1 error) *MockTestResultRepository_CountCompletedByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestResultRepository_CountCompletedByUser_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockTestResultRepository_CountCompletedByUser_Call {
	_c.Call.Return(run)
	return _c
}

// CountMonthlyUsage provides a mock function with given fields: ctx, userID
func (_m *MockTestResultRepository) CountMonthlyUsage(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountMonthlyUsage")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestResultRepository_CountMonthlyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountMonthlyUsage'
type MockTestResultRepository_CountMonthlyUsage_Call struct {
	*mock.Call
}

// CountMonthlyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTestResultRepository_Expecter) CountMonthlyUsage(ctx interface{}, userID interface{}) *MockTestResultRepository_CountMonthlyUsage_Call {
	return &MockTestResultRepository_CountMonthlyUsage_Call{Call: _e.mock.On("CountMonthlyUsage", ctx, userID)}
}

func (_c *MockTestResultRepository_CountMonthlyUsage_Call) Run(run func(ctx context.Context, userID string)) *MockTestResultRepository_CountMonthlyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_CountMonthlyUsage_Call) Return(_a0 int64, _a1 error) *MockTestResultRepository_CountMonthlyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestResultRepository_CountMonthlyUsage_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockTestResultRepository_CountMonthlyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// CountMonthlyUsageByGuestSession provides a mock function with given fields: ctx, guestSessionID
func (_m *MockTestResultRepository) CountMonthlyUsageByGuestSession(ctx context.Context, guestSessionID string) (int64, error) {
	ret := _m.Called(ctx, guestSessionID)

	if len(ret) == 0 {
		panic("no return value specified for CountMonthlyUsageByGuestSession")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, guestSessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, guestSessionID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, guestSessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestResultRepository_CountMonthlyUsageByGuestSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountMonthlyUsageByGuestSession'
type MockTestResultRepository_CountMonthlyUsageByGuestSession_Call struct {
	*mock.Call
}

// CountMonthlyUsageByGuestSession is a helper method to define mock.On call
//   - ctx context.Context
//   - guestSessionID string
func (_e *MockTestResultRepository_Expecter) CountMonthlyUsageByGuestSession(ctx interface{}, guestSessionID interface{}) *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call {
	return &MockTestResultRepository_CountMonthlyUsageByGuestSession_Call{Call: _e.mock.On("CountMonthlyUsageByGuestSession", ctx, guestSessionID)}
}

func (_c *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call) Run(run func(ctx context.Context, guestSessionID string)) *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call) Return(_a0 int64, _a1 error) *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockTestResultRepository_CountMonthlyUsageByGuestSession_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, result
func (_m *MockTestResultRepository) Create(ctx context.Context, result *testresult.TestResult) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *testresult.TestResult) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTestResultRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTestResultRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - result *testresult.TestResult
func (_e *MockTestResultRepository_Expecter) Create(ctx interface{}, result interface{}) *MockTestResultRepository_Create_Call {
	return &MockTestResultRepository_Create_Call{Call: _e.mock.On("Create", ctx, result)}
}

func (_c *MockTestResultRepository_Create_Call) Run(run func(ctx context.Context, result *testresult.TestResult)) *MockTestResultRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*testresult.TestResult))
	})
	return _c
}

func (_c *MockTestResultRepository_Create_Call) Return(_a0 error) *MockTestResultRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTestResultRepository_Create_Call) RunAndReturn(run func(context.Context, *testresult.TestResult) error) *MockTestResultRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function with given fields: ctx, id
func (_m *MockTestResultRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTestResultRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockTestResultRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTestResultRepository_Expecter) DeleteByID(ctx interface{}, id interface{}) *MockTestResultRepository_DeleteByID_Call {
	return &MockTestResultRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockTestResultRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockTestResultRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_DeleteByID_Call) Return(_a0 error) *MockTestResultRepository_DeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTestResultRepository_DeleteByID_Call) RunAndReturn(run func(context.Context, string) error) *MockTestResultRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockTestResultRepository) FindByID(ctx context.Context, id string) (*testresult.TestResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *testresult.TestResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*testresult.TestResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *testresult.TestResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*testresult.TestResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestResultRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTestResultRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTestResultRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTestResultRepository_FindByID_Call {
	return &MockTestResultRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTestResultRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockTestResultRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_FindByID_Call) Return(_a0 *testresult.TestResult, _a1 error) *MockTestResultRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestResultRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*testresult.TestResult, error)) *MockTestResultRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindExpiredGuestResults provides a mock function with given fields: ctx
func (_m *MockTestResultRepository) FindExpiredGuestResults(ctx context.Context) ([]testresult.TestResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiredGuestResults")
	}

	var r0 []testresult.TestResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]testresult.TestResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []testresult.TestResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]testresult.TestResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestResultRepository_FindExpiredGuestResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindExpiredGuestResults'
type MockTestResultRepository_FindExpiredGuestResults_Call struct {
	*mock.Call
}

// FindExpiredGuestResults is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTestResultRepository_Expecter) FindExpiredGuestResults(ctx interface{}) *MockTestResultRepository_FindExpiredGuestResults_Call {
	return &MockTestResultRepository_FindExpiredGuestResults_Call{Call: _e.mock.On("FindExpiredGuestResults", ctx)}
}

func (_c *MockTestResultRepository_FindExpiredGuestResults_Call) Run(run func(ctx context.Context)) *MockTestResultRepository_FindExpiredGuestResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTestResultRepository_FindExpiredGuestResults_Call) Return(_a0 []testresult.TestResult, _a1 error) *MockTestResultRepository_FindExpiredGuestResults_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestResultRepository_FindExpiredGuestResults_Call) RunAndReturn(run func(context.Context) ([]testresult.TestResult, error)) *MockTestResultRepository_FindExpiredGuestResults_Call {
	_c.Call.Return(run)
	return _c
}

// FindHistoryByUser provides a mock function with given fields: ctx, userID, page, limit
func (_m *MockTestResultRepository) FindHistoryByUser(ctx context.Context, userID string, page int, limit int) ([]testresult.TestResult, int64, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindHistoryByUser")
	}

	var r0 []testresult.TestResult
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]testresult.TestResult, int64, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []testresult.TestResult); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]testresult.TestResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, userID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTestResultRepository_FindHistoryByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindHistoryByUser'
type MockTestResultRepository_FindHistoryByUser_Call struct {
	*mock.Call
}

// FindHistoryByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int
//   - limit int
func (_e *MockTestResultRepository_Expecter) FindHistoryByUser(ctx interface{}, userID interface{}, page interface{}, limit interface{}) *MockTestResultRepository_FindHistoryByUser_Call {
	return &MockTestResultRepository_FindHistoryByUser_Call{Call: _e.mock.On("FindHistoryByUser", ctx, userID, page, limit)}
}

func (_c *MockTestResultRepository_FindHistoryByUser_Call) Run(run func(ctx context.Context, userID string, page int, limit int)) *MockTestResultRepository_FindHistoryByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockTestResultRepository_FindHistoryByUser_Call) Return(results []testresult.TestResult, total int64, err error) *MockTestResultRepository_FindHistoryByUser_Call {
	_c.Call.Return(results, total, err)
	return _c
}

func (_c *MockTestResultRepository_FindHistoryByUser_Call) RunAndReturn(run func(context.Context, string, int, int) ([]testresult.TestResult, int64, error)) *MockTestResultRepository_FindHistoryByUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindPDFURLsByUser provides a mock function with given fields: ctx, userID
func (_m *MockTestResultRepository) FindPDFURLsByUser(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindPDFURLsByUser")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestResultRepository_FindPDFURLsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPDFURLsByUser'
type MockTestResultRepository_FindPDFURLsByUser_Call struct {
	*mock.Call
}

// FindPDFURLsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTestResultRepository_Expecter) FindPDFURLsByUser(ctx interface{}, userID interface{}) *MockTestResultRepository_FindPDFURLsByUser_Call {
	return &MockTestResultRepository_FindPDFURLsByUser_Call{Call: _e.mock.On("FindPDFURLsByUser", ctx, userID)}
}

func (_c *MockTestResultRepository_FindPDFURLsByUser_Call) Run(run func(ctx context.Context, userID string)) *MockTestResultRepository_FindPDFURLsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_FindPDFURLsByUser_Call) Return(_a0 []string, _a1 error) *MockTestResultRepository_FindPDFURLsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestResultRepository_FindPDFURLsByUser_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockTestResultRepository_FindPDFURLsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignGuestResults provides a mock function with given fields: ctx, userID, guestSessionID
func (_m *MockTestResultRepository) ReassignGuestResults(ctx context.Context, userID string, guestSessionID string) error {
	ret := _m.Called(ctx, userID, guestSessionID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignGuestResults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, guestSessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTestResultRepository_ReassignGuestResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignGuestResults'
type MockTestResultRepository_ReassignGuestResults_Call struct {
	*mock.Call
}

// ReassignGuestResults is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - guestSessionID string
func (_e *MockTestResultRepository_Expecter) ReassignGuestResults(ctx interface{}, userID interface{}, guestSessionID interface{}) *MockTestResultRepository_ReassignGuestResults_Call {
	return &MockTestResultRepository_ReassignGuestResults_Call{Call: _e.mock.On("ReassignGuestResults", ctx, userID, guestSessionID)}
}

func (_c *MockTestResultRepository_ReassignGuestResults_Call) Run(run func(ctx context.Context, userID string, guestSessionID string)) *MockTestResultRepository_ReassignGuestResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_ReassignGuestResults_Call) Return(_a0 error) *MockTestResultRepository_ReassignGuestResults_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTestResultRepository_ReassignGuestResults_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTestResultRepository_ReassignGuestResults_Call {
	_c.Call.Return(run)
	return _c
}

// ScrubPersonalDataByUser provides a mock function with given fields: ctx, userID
func (_m *MockTestResultRepository) ScrubPersonalDataByUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ScrubPersonalDataByUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTestResultRepository_ScrubPersonalDataByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScrubPersonalDataByUser'
type MockTestResultRepository_ScrubPersonalDataByUser_Call struct {
	*mock.Call
}

// ScrubPersonalDataByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTestResultRepository_Expecter) ScrubPersonalDataByUser(ctx interface{}, userID interface{}) *MockTestResultRepository_ScrubPersonalDataByUser_Call {
	return &MockTestResultRepository_ScrubPersonalDataByUser_Call{Call: _e.mock.On("ScrubPersonalDataByUser", ctx, userID)}
}

func (_c *MockTestResultRepository_ScrubPersonalDataByUser_Call) Run(run func(ctx context.Context, userID string)) *MockTestResultRepository_ScrubPersonalDataByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestResultRepository_ScrubPersonalDataByUser_Call) Return(_a0 error) *MockTestResultRepository_ScrubPersonalDataByUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTestResultRepository_ScrubPersonalDataByUser_Call) RunAndReturn(run func(context.Context, string) error) *MockTestResultRepository_ScrubPersonalDataByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, result
func (_m *MockTestResultRepository) Update(ctx context.Context, result *testresult.TestResult) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *testresult.TestResult) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTestResultRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTestResultRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - result *testresult.TestResult
func (_e *MockTestResultRepository_Expecter) Update(ctx interface{}, result interface{}) *MockTestResultRepository_Update_Call {
	return &MockTestResultRepository_Update_Call{Call: _e.mock.On("Update", ctx, result)}
}

func (_c *MockTestResultRepository_Update_Call) Run(run func(ctx context.Context, result *testresult.TestResult)) *MockTestResultRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*testresult.TestResult))
	})
	return _c
}

func (_c *MockTestResultRepository_Update_Call) Return(_a0 error) *MockTestResultRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTestResultRepository_Update_Call) RunAndReturn(run func(context.Context, *testresult.TestResult) error) *MockTestResultRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePDFStatus provides a mock function with given fields: ctx, id, pdfURL, status
func (_m *MockTestResultRepository) UpdatePDFStatus(ctx context.Context, id string, pdfURL *string, status testresult.PDFStatus) error {
	ret := _m.Called(ctx, id, pdfURL, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePDFStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, testresult.PDFStatus) error); ok {
		r0 = rf(ctx, id, pdfURL, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTestResultRepository_UpdatePDFStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePDFStatus'
type MockTestResultRepository_UpdatePDFStatus_Call struct {
	*mock.Call
}

// UpdatePDFStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - pdfURL *string
//   - status testresult.PDFStatus
func (_e *MockTestResultRepository_Expecter) UpdatePDFStatus(ctx interface{}, id interface{}, pdfURL interface{}, status interface{}) *MockTestResultRepository_UpdatePDFStatus_Call {
	return &MockTestResultRepository_UpdatePDFStatus_Call{Call: _e.mock.On("UpdatePDFStatus", ctx, id, pdfURL, status)}
}

func (_c *MockTestResultRepository_UpdatePDFStatus_Call) Run(run func(ctx context.Context, id string, pdfURL *string, status testresult.PDFStatus)) *MockTestResultRepository_UpdatePDFStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(testresult.PDFStatus))
	})
	return _c
}

func (_c *MockTestResultRepository_UpdatePDFStatus_Call) Return(_a0 error) *MockTestResultRepository_UpdatePDFStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTestResultRepository_UpdatePDFStatus_Call) RunAndReturn(run func(context.Context, string, *string, testresult.PDFStatus) error) *MockTestResultRepository_UpdatePDFStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTestResultRepository creates a new instance of MockTestResultRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestResultRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestResultRepository {
	mock := &MockTestResultRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
