// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	testresult "github.com/aprxty3/your_persona_controller.git/internal/domain/testresult"
	mock "github.com/stretchr/testify/mock"
)

// MockPromptAuditLogRepository is an autogenerated mock type for the PromptAuditLogRepository type
type MockPromptAuditLogRepository struct {
	mock.Mock
}

type MockPromptAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPromptAuditLogRepository) EXPECT() *MockPromptAuditLogRepository_Expecter {
	return &MockPromptAuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, log
func (_m *MockPromptAuditLogRepository) Create(ctx context.Context, log *testresult.PromptAuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *testresult.PromptAuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPromptAuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPromptAuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log *testresult.PromptAuditLog
func (_e *MockPromptAuditLogRepository_Expecter) Create(ctx interface{}, log interface{}) *MockPromptAuditLogRepository_Create_Call {
	return &MockPromptAuditLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *MockPromptAuditLogRepository_Create_Call) Run(run func(ctx context.Context, log *testresult.PromptAuditLog)) *MockPromptAuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*testresult.PromptAuditLog))
	})
	return _c
}

func (_c *MockPromptAuditLogRepository_Create_Call) Return(_a0 error) *MockPromptAuditLogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPromptAuditLogRepository_Create_Call) RunAndReturn(run func(context.Context, *testresult.PromptAuditLog) error) *MockPromptAuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByTestResultID provides a mock function with given fields: ctx, testResultID
func (_m *MockPromptAuditLogRepository) DeleteByTestResultID(ctx context.Context, testResultID string) error {
	ret := _m.Called(ctx, testResultID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTestResultID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, testResultID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPromptAuditLogRepository_DeleteByTestResultID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByTestResultID'
type MockPromptAuditLogRepository_DeleteByTestResultID_Call struct {
	*mock.Call
}

// DeleteByTestResultID is a helper method to define mock.On call
//   - ctx context.Context
//   - testResultID string
func (_e *MockPromptAuditLogRepository_Expecter) DeleteByTestResultID(ctx interface{}, testResultID interface{}) *MockPromptAuditLogRepository_DeleteByTestResultID_Call {
	return &MockPromptAuditLogRepository_DeleteByTestResultID_Call{Call: _e.mock.On("DeleteByTestResultID", ctx, testResultID)}
}

func (_c *MockPromptAuditLogRepository_DeleteByTestResultID_Call) Run(run func(ctx context.Context, testResultID string)) *MockPromptAuditLogRepository_DeleteByTestResultID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPromptAuditLogRepository_DeleteByTestResultID_Call) Return(_a0 error) *MockPromptAuditLogRepository_DeleteByTestResultID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPromptAuditLogRepository_DeleteByTestResultID_Call) RunAndReturn(run func(context.Context, string) error) *MockPromptAuditLogRepository_DeleteByTestResultID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function with given fields: ctx, userID
func (_m *MockPromptAuditLogRepository) DeleteByUserID(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPromptAuditLogRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockPromptAuditLogRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPromptAuditLogRepository_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockPromptAuditLogRepository_DeleteByUserID_Call {
	return &MockPromptAuditLogRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockPromptAuditLogRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockPromptAuditLogRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPromptAuditLogRepository_DeleteByUserID_Call) Return(_a0 error) *MockPromptAuditLogRepository_DeleteByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPromptAuditLogRepository_DeleteByUserID_Call) RunAndReturn(run func(context.Context, string) error) *MockPromptAuditLogRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with given fields: ctx
func (_m *MockPromptAuditLogRepository) DeleteExpired(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPromptAuditLogRepository_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockPromptAuditLogRepository_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPromptAuditLogRepository_Expecter) DeleteExpired(ctx interface{}) *MockPromptAuditLogRepository_DeleteExpired_Call {
	return &MockPromptAuditLogRepository_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx)}
}

func (_c *MockPromptAuditLogRepository_DeleteExpired_Call) Run(run func(ctx context.Context)) *MockPromptAuditLogRepository_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPromptAuditLogRepository_DeleteExpired_Call) Return(_a0 int64, _a1 error) *MockPromptAuditLogRepository_DeleteExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPromptAuditLogRepository_DeleteExpired_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockPromptAuditLogRepository_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPromptAuditLogRepository creates a new instance of MockPromptAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPromptAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPromptAuditLogRepository {
	mock := &MockPromptAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
