// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAIGeneratorService is an autogenerated mock type for the AIGeneratorService type
type MockAIGeneratorService struct {
	mock.Mock
}

type MockAIGeneratorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIGeneratorService) EXPECT() *MockAIGeneratorService_Expecter {
	return &MockAIGeneratorService_Expecter{mock: &_m.Mock}
}

// GenerateSummary provides a mock function with given fields: ctx, text, locale
func (_m *MockAIGeneratorService) GenerateSummary(ctx context.Context, text string, locale string) (string, string, int, error) {
	ret := _m.Called(ctx, text, locale)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSummary")
	}

	var r0 string
	var r1 string
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, string, int, error)); ok {
		return rf(ctx, text, locale)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, text, locale)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, text, locale)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) int); ok {
		r2 = rf(ctx, text, locale)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string) error); ok {
		r3 = rf(ctx, text, locale)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAIGeneratorService_GenerateSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSummary'
type MockAIGeneratorService_GenerateSummary_Call struct {
	*mock.Call
}

// GenerateSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - locale string
func (_e *MockAIGeneratorService_Expecter) GenerateSummary(ctx interface{}, text interface{}, locale interface{}) *MockAIGeneratorService_GenerateSummary_Call {
	return &MockAIGeneratorService_GenerateSummary_Call{Call: _e.mock.On("GenerateSummary", ctx, text, locale)}
}

func (_c *MockAIGeneratorService_GenerateSummary_Call) Run(run func(ctx context.Context, text string, locale string)) *MockAIGeneratorService_GenerateSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAIGeneratorService_GenerateSummary_Call) Return(summary string, rawPrompt string, tokens int, err error) *MockAIGeneratorService_GenerateSummary_Call {
	_c.Call.Return(summary, rawPrompt, tokens, err)
	return _c
}

func (_c *MockAIGeneratorService_GenerateSummary_Call) RunAndReturn(run func(context.Context, string, string) (string, string, int, error)) *MockAIGeneratorService_GenerateSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAIGeneratorService creates a new instance of MockAIGeneratorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIGeneratorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIGeneratorService {
	mock := &MockAIGeneratorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
