// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGeminiBudgetService is an autogenerated mock type for the GeminiBudgetService type
type MockGeminiBudgetService struct {
	mock.Mock
}

type MockGeminiBudgetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGeminiBudgetService) EXPECT() *MockGeminiBudgetService_Expecter {
	return &MockGeminiBudgetService_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function with given fields: ctx, tokens
func (_m *MockGeminiBudgetService) Consume(ctx context.Context, tokens int) error {
	ret := _m.Called(ctx, tokens)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, tokens)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGeminiBudgetService_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockGeminiBudgetService_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - tokens int
func (_e *MockGeminiBudgetService_Expecter) Consume(ctx interface{}, tokens interface{}) *MockGeminiBudgetService_Consume_Call {
	return &MockGeminiBudgetService_Consume_Call{Call: _e.mock.On("Consume", ctx, tokens)}
}

func (_c *MockGeminiBudgetService_Consume_Call) Run(run func(ctx context.Context, tokens int)) *MockGeminiBudgetService_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockGeminiBudgetService_Consume_Call) Return(_a0 error) *MockGeminiBudgetService_Consume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGeminiBudgetService_Consume_Call) RunAndReturn(run func(context.Context, int) error) *MockGeminiBudgetService_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Exceeded provides a mock function with given fields: ctx
func (_m *MockGeminiBudgetService) Exceeded(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Exceeded")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGeminiBudgetService_Exceeded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exceeded'
type MockGeminiBudgetService_Exceeded_Call struct {
	*mock.Call
}

// Exceeded is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGeminiBudgetService_Expecter) Exceeded(ctx interface{}) *MockGeminiBudgetService_Exceeded_Call {
	return &MockGeminiBudgetService_Exceeded_Call{Call: _e.mock.On("Exceeded", ctx)}
}

func (_c *MockGeminiBudgetService_Exceeded_Call) Run(run func(ctx context.Context)) *MockGeminiBudgetService_Exceeded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGeminiBudgetService_Exceeded_Call) Return(_a0 bool, _a1 error) *MockGeminiBudgetService_Exceeded_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGeminiBudgetService_Exceeded_Call) RunAndReturn(run func(context.Context) (bool, error)) *MockGeminiBudgetService_Exceeded_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGeminiBudgetService creates a new instance of MockGeminiBudgetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGeminiBudgetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeminiBudgetService {
	mock := &MockGeminiBudgetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
