// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPDFQueueService is an autogenerated mock type for the PDFQueueService type
type MockPDFQueueService struct {
	mock.Mock
}

type MockPDFQueueService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPDFQueueService) EXPECT() *MockPDFQueueService_Expecter {
	return &MockPDFQueueService_Expecter{mock: &_m.Mock}
}

// EnqueueGeneratePDF provides a mock function with given fields: ctx, testResultID
func (_m *MockPDFQueueService) EnqueueGeneratePDF(ctx context.Context, testResultID string) error {
	ret := _m.Called(ctx, testResultID)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueGeneratePDF")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, testResultID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPDFQueueService_EnqueueGeneratePDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueGeneratePDF'
type MockPDFQueueService_EnqueueGeneratePDF_Call struct {
	*mock.Call
}

// EnqueueGeneratePDF is a helper method to define mock.On call
//   - ctx context.Context
//   - testResultID string
func (_e *MockPDFQueueService_Expecter) EnqueueGeneratePDF(ctx interface{}, testResultID interface{}) *MockPDFQueueService_EnqueueGeneratePDF_Call {
	return &MockPDFQueueService_EnqueueGeneratePDF_Call{Call: _e.mock.On("EnqueueGeneratePDF", ctx, testResultID)}
}

func (_c *MockPDFQueueService_EnqueueGeneratePDF_Call) Run(run func(ctx context.Context, testResultID string)) *MockPDFQueueService_EnqueueGeneratePDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPDFQueueService_EnqueueGeneratePDF_Call) Return(_a0 error) *MockPDFQueueService_EnqueueGeneratePDF_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPDFQueueService_EnqueueGeneratePDF_Call) RunAndReturn(run func(context.Context, string) error) *MockPDFQueueService_EnqueueGeneratePDF_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPDFQueueService creates a new instance of MockPDFQueueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPDFQueueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPDFQueueService {
	mock := &MockPDFQueueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
