// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/aprxty3/your_persona_controller.git/internal/application/assessment/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockIPRateLimiter is an autogenerated mock type for the IPRateLimiter type
type MockIPRateLimiter struct {
	mock.Mock
}

type MockIPRateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPRateLimiter) EXPECT() *MockIPRateLimiter_Expecter {
	return &MockIPRateLimiter_Expecter{mock: &_m.Mock}
}

// Allow provides a mock function with given fields: ctx, scope, ip
func (_m *MockIPRateLimiter) Allow(ctx context.Context, scope dto.IPRateLimitScope, ip string) (bool, int, error) {
	ret := _m.Called(ctx, scope, ip)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 bool
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.IPRateLimitScope, string) (bool, int, error)); ok {
		return rf(ctx, scope, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.IPRateLimitScope, string) bool); ok {
		r0 = rf(ctx, scope, ip)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.IPRateLimitScope, string) int); ok {
		r1 = rf(ctx, scope, ip)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.IPRateLimitScope, string) error); ok {
		r2 = rf(ctx, scope, ip)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIPRateLimiter_Allow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allow'
type MockIPRateLimiter_Allow_Call struct {
	*mock.Call
}

// Allow is a helper method to define mock.On call
//   - ctx context.Context
//   - scope dto.IPRateLimitScope
//   - ip string
func (_e *MockIPRateLimiter_Expecter) Allow(ctx interface{}, scope interface{}, ip interface{}) *MockIPRateLimiter_Allow_Call {
	return &MockIPRateLimiter_Allow_Call{Call: _e.mock.On("Allow", ctx, scope, ip)}
}

func (_c *MockIPRateLimiter_Allow_Call) Run(run func(ctx context.Context, scope dto.IPRateLimitScope, ip string)) *MockIPRateLimiter_Allow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.IPRateLimitScope), args[2].(string))
	})
	return _c
}

func (_c *MockIPRateLimiter_Allow_Call) Return(allowed bool, retryAfterSeconds int, err error) *MockIPRateLimiter_Allow_Call {
	_c.Call.Return(allowed, retryAfterSeconds, err)
	return _c
}

func (_c *MockIPRateLimiter_Allow_Call) RunAndReturn(run func(context.Context, dto.IPRateLimitScope, string) (bool, int, error)) *MockIPRateLimiter_Allow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPRateLimiter creates a new instance of MockIPRateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPRateLimiter {
	mock := &MockIPRateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
