// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockPDFSignerService is an autogenerated mock type for the PDFSignerService type
type MockPDFSignerService struct {
	mock.Mock
}

type MockPDFSignerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPDFSignerService) EXPECT() *MockPDFSignerService_Expecter {
	return &MockPDFSignerService_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields: ctx, objectURL
func (_m *MockPDFSignerService) Download(ctx context.Context, objectURL string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, objectURL)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, objectURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, objectURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objectURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPDFSignerService_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockPDFSignerService_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - objectURL string
func (_e *MockPDFSignerService_Expecter) Download(ctx interface{}, objectURL interface{}) *MockPDFSignerService_Download_Call {
	return &MockPDFSignerService_Download_Call{Call: _e.mock.On("Download", ctx, objectURL)}
}

func (_c *MockPDFSignerService_Download_Call) Run(run func(ctx context.Context, objectURL string)) *MockPDFSignerService_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPDFSignerService_Download_Call) Return(_a0 io.ReadCloser, _a1 error) *MockPDFSignerService_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPDFSignerService_Download_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockPDFSignerService_Download_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPDFSignerService creates a new instance of MockPDFSignerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPDFSignerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPDFSignerService {
	mock := &MockPDFSignerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
