// Code generated by mockery v2.53.6. DO NOT EDIT.

package pdf

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPDFRenderer is an autogenerated mock type for the PDFRenderer type
type MockPDFRenderer struct {
	mock.Mock
}

type MockPDFRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPDFRenderer) EXPECT() *MockPDFRenderer_Expecter {
	return &MockPDFRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function with given fields: ctx, data
func (_m *MockPDFRenderer) Render(ctx context.Context, data PDFData) ([]byte, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, PDFData) ([]byte, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, PDFData) []byte); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, PDFData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPDFRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockPDFRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - ctx context.Context
//   - data PDFData
func (_e *MockPDFRenderer_Expecter) Render(ctx interface{}, data interface{}) *MockPDFRenderer_Render_Call {
	return &MockPDFRenderer_Render_Call{Call: _e.mock.On("Render", ctx, data)}
}

func (_c *MockPDFRenderer_Render_Call) Run(run func(ctx context.Context, data PDFData)) *MockPDFRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(PDFData))
	})
	return _c
}

func (_c *MockPDFRenderer_Render_Call) Return(_a0 []byte, _a1 error) *MockPDFRenderer_Render_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPDFRenderer_Render_Call) RunAndReturn(run func(context.Context, PDFData) ([]byte, error)) *MockPDFRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPDFRenderer creates a new instance of MockPDFRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPDFRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPDFRenderer {
	mock := &MockPDFRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
