// Code generated by mockery v2.53.6. DO NOT EDIT.

package pdf

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPDFUploader is an autogenerated mock type for the PDFUploader type
type MockPDFUploader struct {
	mock.Mock
}

type MockPDFUploader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPDFUploader) EXPECT() *MockPDFUploader_Expecter {
	return &MockPDFUploader_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function with given fields: ctx, key, data, contentType
func (_m *MockPDFUploader) Upload(ctx context.Context, key string, data []byte, contentType string) (string, error) {
	ret := _m.Called(ctx, key, data, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) (string, error)); ok {
		return rf(ctx, key, data, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) string); ok {
		r0 = rf(ctx, key, data, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, string) error); ok {
		r1 = rf(ctx, key, data, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPDFUploader_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockPDFUploader_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data []byte
//   - contentType string
func (_e *MockPDFUploader_Expecter) Upload(ctx interface{}, key interface{}, data interface{}, contentType interface{}) *MockPDFUploader_Upload_Call {
	return &MockPDFUploader_Upload_Call{Call: _e.mock.On("Upload", ctx, key, data, contentType)}
}

func (_c *MockPDFUploader_Upload_Call) Run(run func(ctx context.Context, key string, data []byte, contentType string)) *MockPDFUploader_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *MockPDFUploader_Upload_Call) Return(url string, err error) *MockPDFUploader_Upload_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockPDFUploader_Upload_Call) RunAndReturn(run func(context.Context, string, []byte, string) (string, error)) *MockPDFUploader_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPDFUploader creates a new instance of MockPDFUploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPDFUploader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPDFUploader {
	mock := &MockPDFUploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
