// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	content "github.com/aprxty3/your_persona_controller.git/internal/domain/content"

	mock "github.com/stretchr/testify/mock"
)

// MockQuestionRepository is an autogenerated mock type for the QuestionRepository type
type MockQuestionRepository struct {
	mock.Mock
}

type MockQuestionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuestionRepository) EXPECT() *MockQuestionRepository_Expecter {
	return &MockQuestionRepository_Expecter{mock: &_m.Mock}
}

// FindAllWithTranslation provides a mock function with given fields: ctx, locale
func (_m *MockQuestionRepository) FindAllWithTranslation(ctx context.Context, locale string) ([]content.Question, map[string]content.QuestionTranslation, error) {
	ret := _m.Called(ctx, locale)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithTranslation")
	}

	var r0 []content.Question
	var r1 map[string]content.QuestionTranslation
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]content.Question, map[string]content.QuestionTranslation, error)); ok {
		return rf(ctx, locale)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []content.Question); ok {
		r0 = rf(ctx, locale)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]content.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) map[string]content.QuestionTranslation); ok {
		r1 = rf(ctx, locale)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]content.QuestionTranslation)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, locale)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockQuestionRepository_FindAllWithTranslation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllWithTranslation'
type MockQuestionRepository_FindAllWithTranslation_Call struct {
	*mock.Call
}

// FindAllWithTranslation is a helper method to define mock.On call
//   - ctx context.Context
//   - locale string
func (_e *MockQuestionRepository_Expecter) FindAllWithTranslation(ctx interface{}, locale interface{}) *MockQuestionRepository_FindAllWithTranslation_Call {
	return &MockQuestionRepository_FindAllWithTranslation_Call{Call: _e.mock.On("FindAllWithTranslation", ctx, locale)}
}

func (_c *MockQuestionRepository_FindAllWithTranslation_Call) Run(run func(ctx context.Context, locale string)) *MockQuestionRepository_FindAllWithTranslation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuestionRepository_FindAllWithTranslation_Call) Return(_a0 []content.Question, _a1 map[string]content.QuestionTranslation, _a2 error) *MockQuestionRepository_FindAllWithTranslation_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockQuestionRepository_FindAllWithTranslation_Call) RunAndReturn(run func(context.Context, string) ([]content.Question, map[string]content.QuestionTranslation, error)) *MockQuestionRepository_FindAllWithTranslation_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockQuestionRepository) FindByID(ctx context.Context, id string) (*content.Question, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *content.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*content.Question, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *content.Question); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuestionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockQuestionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockQuestionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockQuestionRepository_FindByID_Call {
	return &MockQuestionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockQuestionRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockQuestionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuestionRepository_FindByID_Call) Return(_a0 *content.Question, _a1 error) *MockQuestionRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuestionRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*content.Question, error)) *MockQuestionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function with given fields: ctx, ids
func (_m *MockQuestionRepository) FindByIDs(ctx context.Context, ids []string) ([]content.Question, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []content.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]content.Question, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []content.Question); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]content.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuestionRepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockQuestionRepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockQuestionRepository_Expecter) FindByIDs(ctx interface{}, ids interface{}) *MockQuestionRepository_FindByIDs_Call {
	return &MockQuestionRepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockQuestionRepository_FindByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockQuestionRepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockQuestionRepository_FindByIDs_Call) Return(_a0 []content.Question, _a1 error) *MockQuestionRepository_FindByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuestionRepository_FindByIDs_Call) RunAndReturn(run func(context.Context, []string) ([]content.Question, error)) *MockQuestionRepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuestionRepository creates a new instance of MockQuestionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuestionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuestionRepository {
	mock := &MockQuestionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
