// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	content "github.com/aprxty3/your_persona_controller.git/internal/domain/content"

	mock "github.com/stretchr/testify/mock"
)

// MockInsightTemplateRepository is an autogenerated mock type for the InsightTemplateRepository type
type MockInsightTemplateRepository struct {
	mock.Mock
}

type MockInsightTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInsightTemplateRepository) EXPECT() *MockInsightTemplateRepository_Expecter {
	return &MockInsightTemplateRepository_Expecter{mock: &_m.Mock}
}

// FindMatchingTemplates provides a mock function with given fields: ctx, trait, locale
func (_m *MockInsightTemplateRepository) FindMatchingTemplates(ctx context.Context, trait string, locale string) ([]content.InsightTemplate, error) {
	ret := _m.Called(ctx, trait, locale)

	if len(ret) == 0 {
		panic("no return value specified for FindMatchingTemplates")
	}

	var r0 []content.InsightTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]content.InsightTemplate, error)); ok {
		return rf(ctx, trait, locale)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []content.InsightTemplate); ok {
		r0 = rf(ctx, trait, locale)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]content.InsightTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, trait, locale)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInsightTemplateRepository_FindMatchingTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMatchingTemplates'
type MockInsightTemplateRepository_FindMatchingTemplates_Call struct {
	*mock.Call
}

// FindMatchingTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - trait string
//   - locale string
func (_e *MockInsightTemplateRepository_Expecter) FindMatchingTemplates(ctx interface{}, trait interface{}, locale interface{}) *MockInsightTemplateRepository_FindMatchingTemplates_Call {
	return &MockInsightTemplateRepository_FindMatchingTemplates_Call{Call: _e.mock.On("FindMatchingTemplates", ctx, trait, locale)}
}

func (_c *MockInsightTemplateRepository_FindMatchingTemplates_Call) Run(run func(ctx context.Context, trait string, locale string)) *MockInsightTemplateRepository_FindMatchingTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInsightTemplateRepository_FindMatchingTemplates_Call) Return(_a0 []content.InsightTemplate, _a1 error) *MockInsightTemplateRepository_FindMatchingTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInsightTemplateRepository_FindMatchingTemplates_Call) RunAndReturn(run func(context.Context, string, string) ([]content.InsightTemplate, error)) *MockInsightTemplateRepository_FindMatchingTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInsightTemplateRepository creates a new instance of MockInsightTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInsightTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInsightTemplateRepository {
	mock := &MockInsightTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
