// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	content "github.com/aprxty3/your_persona_controller.git/internal/domain/content"

	mock "github.com/stretchr/testify/mock"
)

// MockQuestionTranslationRepository is an autogenerated mock type for the QuestionTranslationRepository type
type MockQuestionTranslationRepository struct {
	mock.Mock
}

type MockQuestionTranslationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuestionTranslationRepository) EXPECT() *MockQuestionTranslationRepository_Expecter {
	return &MockQuestionTranslationRepository_Expecter{mock: &_m.Mock}
}

// FindByQuestionAndLocale provides a mock function with given fields: ctx, questionID, locale
func (_m *MockQuestionTranslationRepository) FindByQuestionAndLocale(ctx context.Context, questionID string, locale string) (*content.QuestionTranslation, error) {
	ret := _m.Called(ctx, questionID, locale)

	if len(ret) == 0 {
		panic("no return value specified for FindByQuestionAndLocale")
	}

	var r0 *content.QuestionTranslation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*content.QuestionTranslation, error)); ok {
		return rf(ctx, questionID, locale)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *content.QuestionTranslation); ok {
		r0 = rf(ctx, questionID, locale)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.QuestionTranslation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, questionID, locale)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuestionTranslationRepository_FindByQuestionAndLocale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByQuestionAndLocale'
type MockQuestionTranslationRepository_FindByQuestionAndLocale_Call struct {
	*mock.Call
}

// FindByQuestionAndLocale is a helper method to define mock.On call
//   - ctx context.Context
//   - questionID string
//   - locale string
func (_e *MockQuestionTranslationRepository_Expecter) FindByQuestionAndLocale(ctx interface{}, questionID interface{}, locale interface{}) *MockQuestionTranslationRepository_FindByQuestionAndLocale_Call {
	return &MockQuestionTranslationRepository_FindByQuestionAndLocale_Call{Call: _e.mock.On("FindByQuestionAndLocale", ctx, questionID, locale)}
}

func (_c *MockQuestionTranslationRepository_FindByQuestionAndLocale_Call) Run(run func(ctx context.Context, questionID string, locale string)) *MockQuestionTranslationRepository_FindByQuestionAndLocale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockQuestionTranslationRepository_FindByQuestionAndLocale_Call) Return(_a0 *content.QuestionTranslation, _a1 error) *MockQuestionTranslationRepository_FindByQuestionAndLocale_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuestionTranslationRepository_FindByQuestionAndLocale_Call) RunAndReturn(run func(context.Context, string, string) (*content.QuestionTranslation, error)) *MockQuestionTranslationRepository_FindByQuestionAndLocale_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertTranslation provides a mock function with given fields: ctx, translation
func (_m *MockQuestionTranslationRepository) UpsertTranslation(ctx context.Context, translation *content.QuestionTranslation) error {
	ret := _m.Called(ctx, translation)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTranslation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *content.QuestionTranslation) error); ok {
		r0 = rf(ctx, translation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuestionTranslationRepository_UpsertTranslation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertTranslation'
type MockQuestionTranslationRepository_UpsertTranslation_Call struct {
	*mock.Call
}

// UpsertTranslation is a helper method to define mock.On call
//   - ctx context.Context
//   - translation *content.QuestionTranslation
func (_e *MockQuestionTranslationRepository_Expecter) UpsertTranslation(ctx interface{}, translation interface{}) *MockQuestionTranslationRepository_UpsertTranslation_Call {
	return &MockQuestionTranslationRepository_UpsertTranslation_Call{Call: _e.mock.On("UpsertTranslation", ctx, translation)}
}

func (_c *MockQuestionTranslationRepository_UpsertTranslation_Call) Run(run func(ctx context.Context, translation *content.QuestionTranslation)) *MockQuestionTranslationRepository_UpsertTranslation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*content.QuestionTranslation))
	})
	return _c
}

func (_c *MockQuestionTranslationRepository_UpsertTranslation_Call) Return(_a0 error) *MockQuestionTranslationRepository_UpsertTranslation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuestionTranslationRepository_UpsertTranslation_Call) RunAndReturn(run func(context.Context, *content.QuestionTranslation) error) *MockQuestionTranslationRepository_UpsertTranslation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuestionTranslationRepository creates a new instance of MockQuestionTranslationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuestionTranslationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuestionTranslationRepository {
	mock := &MockQuestionTranslationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
